# -*- coding: utf-8 -*-
"""linguistic_analysis_of_salient_words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZW8AunmsqNmSs9Kra7i3i9Dr4hAaaTKF

# Computing POS tags and Dependency Distances for Salient Words

Upload file ``POS_data_relative20``
"""

from google.colab import files

# Upload file
uploaded = files.upload()

!python -m spacy download en_core_web_lg

"""## Define Utils Functions"""

import pandas as pd
import spacy
import json
import matplotlib.pyplot as plt
from collections import Counter
import numpy as np

# Load spaCy English model
nlp = spacy.load('en_core_web_lg')


def find_target_tokens(doc, target_word):
    """Find target word tokens, handling multi-word targets like 'flight attendant'."""
    target_words = target_word.lower().split()

    if len(target_words) == 1:
        # Single word target
        for token in doc:
            if token.text.lower() == target_words[0]:
                return [token]
    else:
        # Multi-word target - find consecutive tokens
        for i in range(len(doc) - len(target_words) + 1):
            match = True
            for j, target_part in enumerate(target_words):
                if doc[i + j].text.lower() != target_part:
                    match = False
                    break
            if match:
                # Return all tokens that make up the target phrase
                return [doc[i + j] for j in range(len(target_words))]

    return []


def find_salient_token(doc, salient_word):
    """Find salient word token, handling punctuation, contractions, and hyphenated words."""
    salient_lower = salient_word.lower().strip()

    # Try exact match first
    for token in doc:
        if token.text.lower() == salient_lower:
            return token

    # Try matching with lemma (base form)
    for token in doc:
        if token.lemma_.lower() == salient_lower:
            return token

    # Handle hyphenated words by finding token sequences
    if '-' in salient_lower:
        hyphen_result = find_hyphenated_sequence(doc, salient_lower)
        if hyphen_result:
            return hyphen_result

    # Handle contractions and possessives by finding token sequences
    if "'" in salient_lower:
        contraction_result = find_contraction_sequence(doc, salient_lower)
        if contraction_result:
            return contraction_result

    # More comprehensive matching for other cases
    for token in doc:
        token_text = token.text.lower()

        # 1. Clean token by removing trailing punctuation
        token_clean = token_text.rstrip('.,!?;:"\'()[]{}')
        if token_clean == salient_lower:
            return token

        # 2. Handle single letters (like 'C')
        if len(salient_lower) == 1:
            if token_clean == salient_lower:
                return token
            # For single letters, also check if token starts with the letter
            if token_text.startswith(salient_lower) and len(token_clean) == 1:
                return token
            # Special case: look for "D.C" when looking for "C"
            if salient_lower == 'c' and ('d.c' in token_text or 'dc' in token_clean):
                return token

        # 3. Try matching by removing all punctuation from both
        import string
        salient_no_punct = salient_lower.translate(str.maketrans('', '', string.punctuation))
        token_no_punct = token_text.translate(str.maketrans('', '', string.punctuation))
        if salient_no_punct and token_no_punct and salient_no_punct == token_no_punct:
            return token

    return None

def find_hyphenated_sequence(doc, hyphenated_word):
    """Find a sequence of tokens that make up a hyphenated word."""
    parts = hyphenated_word.split('-')

    for i in range(len(doc) - (len(parts) * 2 - 1) + 1):
        match = True
        token_idx = i

        for j, part in enumerate(parts):
            if token_idx >= len(doc) or doc[token_idx].text.lower() != part.lower():
                match = False
                break

            token_idx += 1

            if j < len(parts) - 1:
                if token_idx >= len(doc) or doc[token_idx].text != '-':
                    match = False
                    break
                token_idx += 1

        if match:
            return doc[i]

    return None

def find_contraction_sequence(doc, contraction_word):
    """Find a sequence of tokens that make up a contraction or possessive."""
    contraction_lower = contraction_word.lower()

    if contraction_lower.endswith("'s"):
        base_word = contraction_lower[:-2]
        result = find_word_apostrophe_sequence(doc, base_word, "'s")
        if result:
            return result
        # Fallback: just find the base word
        return find_base_word_fallback(doc, base_word)

    elif contraction_lower.endswith("'m"):
        base_word = contraction_lower[:-2]
        result = find_word_apostrophe_sequence(doc, base_word, "'m")
        if result:
            return result
        return find_base_word_fallback(doc, base_word)

    elif contraction_lower.endswith("'re"):
        base_word = contraction_lower[:-3]
        result = find_word_apostrophe_sequence(doc, base_word, "'re")
        if result:
            return result
        return find_base_word_fallback(doc, base_word)

    elif contraction_lower.endswith("'ll"):
        base_word = contraction_lower[:-3]
        result = find_word_apostrophe_sequence(doc, base_word, "'ll")
        if result:
            return result
        return find_base_word_fallback(doc, base_word)

    elif contraction_lower.endswith("'ve"):
        base_word = contraction_lower[:-3]
        result = find_word_apostrophe_sequence(doc, base_word, "'ve")
        if result:
            return result
        return find_base_word_fallback(doc, base_word)

    elif contraction_lower.endswith("'d"):
        base_word = contraction_lower[:-2]
        result = find_word_apostrophe_sequence(doc, base_word, "'d")
        if result:
            return result
        return find_base_word_fallback(doc, base_word)

    return None


def find_base_word_fallback(doc, base_word):
    """Fallback function to find just the base word if contraction sequence fails."""
    print(f"  DEBUG: Falling back to finding just base word '{base_word}'")

    for token in doc:
        if token.text.lower() == base_word.lower():
            print(f"  DEBUG: Found base word fallback: '{token.text}' (POS: {token.pos_})")
            return token

    print(f"  DEBUG: Base word fallback failed for '{base_word}'")
    return None

def find_word_apostrophe_sequence(doc, base_word, apostrophe_part):
    """Find a sequence like ['word', \"'s\"] or ['I', \"'m\"]."""
    # Debug: print what we're looking for and what's available
    print(f"  DEBUG: Looking for base_word='{base_word}' + apostrophe_part='{apostrophe_part}'")

    for i in range(len(doc) - 1):
        current_token = doc[i].text.lower()
        next_token = doc[i + 1].text

        print(f"  DEBUG: Checking tokens[{i}]='{doc[i].text}' (lower: '{current_token}') + tokens[{i+1}]='{doc[i + 1].text}' (repr: {repr(next_token)})")

        # Check if current token matches base word
        if current_token == base_word.lower():
            print(f"  DEBUG: Base word '{base_word}' matches token '{doc[i].text}'")

            # Now check apostrophe part - be very flexible with matching
            if (next_token == apostrophe_part or
                next_token.lower() == apostrophe_part.lower() or
                next_token == "'s" or  # regular apostrophe
                next_token == "'s" or  # smart quote
                next_token == "′s" or  # prime symbol
                next_token == "`s" or  # backtick
                (apostrophe_part.lower() == "'s" and next_token in ["'s", "'s", "′s", "`s"]) or
                (apostrophe_part.lower() == "'m" and next_token in ["'m", "'m", "′m", "`m"]) or
                (apostrophe_part.lower() == "'re" and next_token in ["'re", "'re", "′re", "`re"]) or
                (apostrophe_part.lower() == "'ll" and next_token in ["'ll", "'ll", "′ll", "`ll"]) or
                (apostrophe_part.lower() == "'ve" and next_token in ["'ve", "'ve", "′ve", "`ve"]) or
                (apostrophe_part.lower() == "'d" and next_token in ["'d", "'d", "′d", "`d"])):

                print(f"  DEBUG: Found match! Base='{doc[i].text}' + Apostrophe='{next_token}'")
                return doc[i]
            else:
                print(f"  DEBUG: Base word matches but apostrophe part '{next_token}' doesn't match expected '{apostrophe_part}'")

    print(f"  DEBUG: No match found for '{base_word}' + '{apostrophe_part}'")
    return None

"""## Calculate average POS of salient words

Define Function to Calculate and Display Average POS Frequencies: (i) Among All Words, (ii) Among only Salient Words
"""

def calculate_average_pos_percentage(data):
    """
    Calculate POS tag percentages per all words / per salient words.

    Parameters:
    - data: Requires 'POS_data_relative20.txt' file with relevant columns.
    """
    all_pos_counts_all = Counter()
    all_pos_counts_labeled = Counter()

    total_processed = 0
    total_found = 0
    total_not_found = 0

    for index, row in data.iterrows():
        text = row['EN_source']
        salient_words_str = row.get('salient_words', '')

        # Skip if any required field is missing or empty
        if pd.isna(text) or pd.isna(salient_words_str):
            continue

        total_processed += 1

        # Parse the text with spaCy
        doc = nlp(text)

        # Count all POS tags in the text
        for token in doc:
            if not token.is_space:  # Skip whitespace tokens
                pos_label = token.pos_
                all_pos_counts_all[pos_label] += 1

        # Split salient words by semicolon and clean them
        salient_words_list = [word.strip() for word in salient_words_str.split(';') if word.strip()]

        # For each salient word, find it in the text and count its POS
        for salient_word in salient_words_list:
            salient_token = find_salient_token(doc, salient_word)

            if salient_token:
                pos_label = salient_token.pos_
                all_pos_counts_labeled[pos_label] += 1
                total_found += 1
            else:
                total_not_found += 1
                print(f"Salient word '{salient_word}' not found in text: {text[:50]}...")

                # Enhanced debugging for contractions
                if "'" in salient_word:
                    print(f"  DEBUG: Apostrophe word - analyzing tokenization...")
                    tokens_with_indices = [(i, token.text, repr(token.text)) for i, token in enumerate(doc)]
                    print(f"  DEBUG: All tokens with repr: {tokens_with_indices}")

                    # Show character codes for apostrophe characters
                    for char in salient_word:
                        if char in "''′`":
                            print(f"  DEBUG: Apostrophe character '{char}' has Unicode code: {ord(char)}")

                # Show available tokens
                tokens_in_text = [token.text for token in doc]
                print(f"  Available tokens: {tokens_in_text}")
                similar_tokens = [token.text for token in doc if salient_word.lower().replace("'", "").replace("'", "") in token.text.lower() or token.text.lower() in salient_word.lower().replace("'", "").replace("'", "")]
                if similar_tokens:
                    print(f"  Similar tokens found: {similar_tokens}")

    print("\nPOS Tags andFrequency")

    # Calculate percentages for each POS tag of all words
    pos_percentages_all = {}
    for pos in all_pos_counts_all:
        total_count = all_pos_counts_all[pos]
        labeled_count = all_pos_counts_labeled[pos]
        percentage = (labeled_count / total_count) * 100 if total_count > 0 else 0
        pos_percentages_all[pos] = percentage
        print(f"{pos}: {labeled_count}/{total_count} = {percentage:.2f}%")

    # Calculate percentages for each POS tag among salient words
    pos_percentages_salient = {}
    for pos in all_pos_counts_labeled:
        #total_count = all_pos_counts_all[pos]
        labeled_count = all_pos_counts_labeled[pos]
        percentage = (labeled_count / total_found) * 100 if total_found > 0 else 0
        pos_percentages_salient[pos] = percentage
        print(f"{pos}: {labeled_count}/{total_found} = {percentage:.2f}%")

    print(f"\nSummary:")
    print(f"Total rows processed: {total_processed}")
    print(f"Total salient words found: {total_found}")
    print(f"Total salient words not found: {total_not_found}")
    print(f"Total POS tags in all texts: {sum(all_pos_counts_all.values())}")
    print(f"Total POS tags of salient words: {sum(all_pos_counts_labeled.values())}")

    # Display results in a bar chart
  # Display results in bar charts
    print("\n")
    display_average_pos_chart(pos_percentages_all, title="POS Tag Distribution: Salient Words vs All Words", show_percent_symbol=True)
    print("\n\n")
    display_average_pos_chart(pos_percentages_salient, title="POS Tag Distribution of Salient Words", show_percent_symbol=False)


    return pos_percentages_all, pos_percentages_salient, all_pos_counts_all, all_pos_counts_labeled


def display_average_pos_chart(pos_percentages, title, show_percent_symbol=True):
    """
    Display POS tag distribution chart with customizable labels.

    Parameters:
    - pos_percentages: dict of POS tags and their percentages
    - title: Chart title
    - show_percent_symbol: Whether to add '%' to bar labels
    """
    filtered_data = {pos: perc for pos, perc in pos_percentages.items() if perc > 0}

    if not filtered_data:
        print("No POS tags found for salient words")
        return

    sorted_items = sorted(filtered_data.items(), key=lambda x: x[1], reverse=True)
    labels, values = zip(*sorted_items)
    colors = plt.cm.viridis(np.linspace(0, 1, len(labels)))
    xlabel="Percentage of Salient Words with this POS Tag (%)"

    plt.figure(figsize=(12, 8))
    bars = plt.barh(labels, values, color=colors)

    # Add percentage labels on bars
    #label_format = f'{{}:.1f}%' if show_percent_symbol else f'{{}:.1f}'
    for i, (bar, value) in enumerate(zip(bars, values)):
        plt.text(value + 0.5, bar.get_y() + bar.get_height()/2,
                f'{value:.1f}%',  ha='left', va='center',
                fontweight='bold', fontsize=20)

    plt.title(title, fontsize=24, fontweight='medium')
    plt.xlabel(xlabel, fontsize=24, fontweight='medium')
    plt.ylabel("POS Tags", fontsize=24, fontweight='medium')
    plt.tick_params(axis='both', which='major', labelsize=20)

    plt.tight_layout()
    plt.grid(axis='x', alpha=0.3)
    plt.show()

# Load the data from a tab-separated text file
data = pd.read_csv('/content/POS_data_relative20.txt', sep='\t', encoding='windows-1252')

# Display basic info about the data
print(f"Data shape: {data.shape}")
print(f"Columns: {list(data.columns)}")
print("\nFirst few rows of relevant columns:")
print(data[['EN_source', 'target_word', 'salient_words']].head())

print("\n" + "="*50)
print("CALCULATING POS TAG PERCENTAGES")
print("="*50)

# Run function to calculate POS frequency distribution among salient words
pos_percentages_all, pos_percentage_of_salient_words, all_counts, labeled_counts = calculate_average_pos_percentage(data)

"""## Calculate dependency distances of salient words"""

def avg_dependencies_distance(data):
    """
    Calculate POS tag percentages per all words / per salient words.

    Parameters:
    - data: Requires 'POS_data_relative20.txt' file with relevant columns.
    """
    all_distances = []

    for index, row in data.iterrows():
        text = row['EN_source']
        target_word = row['target_word']
        salient_words_str = row.get('salient_words', '')  # Get salient words string

        # Skip if any required field is missing or empty
        if pd.isna(text) or pd.isna(target_word) or pd.isna(salient_words_str):
            continue

        # Parse the text with spaCy
        doc = nlp(text)

        # Find the target word token(s) - handle multi-word targets
        target_tokens = find_target_tokens(doc, target_word)

        # If target word is not found, skip this entry
        if not target_tokens:
            print(f"Target word '{target_word}' not found in text: {text[:50]}...")
            continue

        # Split salient words by semicolon and clean them
        salient_words_list = [word.strip() for word in salient_words_str.split(';') if word.strip()]

        # For each salient word, find it in the text and calculate distance
        for salient_word in salient_words_list:
            # Find the salient word token in the document
            salient_token = find_salient_token(doc, salient_word)

            # If salient word is found, calculate distance to each target token
            if salient_token:
                for target_token in target_tokens:
                    distance = find_distance(target_token, salient_token, doc)
                    if distance is not None and distance > 0:
                        print(f"Distance from '{salient_token}' to '{target_token}': {distance}")
                        all_distances.append(distance)
            else:
                # Debug: show what tokens are actually in the text around the expected word
                print(f"Salient word '{salient_word}' not found in text: {text[:50]}...")
                # Show all tokens for debugging
                tokens_in_text = [token.text for token in doc]
                print(f"  Available tokens: {tokens_in_text}")
                # Try to find similar tokens
                similar_tokens = [token.text for token in doc if salient_word.lower() in token.text.lower() or token.text.lower() in salient_word.lower()]
                if similar_tokens:
                    print(f"  Similar tokens found: {similar_tokens}")

    # Turn the list of all distances into a dictionary with distances and their frequencies
    distance_frequency = Counter(all_distances)

    # Calculate average frequency for each distance (dividing by total number of rows)
    total_entries = len(data)
    average_distance_frequency = {distance: count / total_entries for distance, count in distance_frequency.items()}

    print(f"\nTotal distances calculated: {len(all_distances)}")
    print(f"Distance frequency: {dict(distance_frequency)}")
    print(f"Average distance frequency: {dict(average_distance_frequency)}")

    print("\n")
    # Display the chart
    display_dep_freq_chart(average_distance_frequency)


def find_distance(word1, word2, doc):
    """Calculate distance in the dependency tree."""

    # Create a mapping of token index to its head (parent) index
    token_to_head = {token.i: token.head.i for token in doc}

    # Function to find the path from a word to the root
    def get_path_to_root(token_idx):
        path = []
        visited = set()  # Prevent infinite loops
        while token_idx != token_to_head[token_idx] and token_idx not in visited:
            visited.add(token_idx)
            path.append(token_idx)
            token_idx = token_to_head[token_idx]
        path.append(token_idx)
        return path

    # Get the paths from both words to the root
    path1 = get_path_to_root(word1.i)
    path2 = get_path_to_root(word2.i)

    # Find the common ancestor
    common_ancestor = None
    for token in path1:
        if token in path2:
            common_ancestor = token
            break

    # Calculate distance only if common ancestor is found in both paths
    if common_ancestor is not None and common_ancestor in path1 and common_ancestor in path2:
        distance = path1.index(common_ancestor) + path2.index(common_ancestor)
        return distance
    else:
        # Handle case where common ancestor is not found
        return None


# PLOT the distances and frequencies
def display_dep_freq_chart(distance_frequency):
    # Filter out 0 and None from labels and values
    filtered_labels = [label for label in distance_frequency if label and label != 0]
    filtered_values = [distance_frequency[label] for label in filtered_labels]

    if not filtered_labels:
        print("No valid distances to plot")
        return

    # Sort by distance for better visualization
    sorted_pairs = sorted(zip(filtered_labels, filtered_values))
    filtered_labels, filtered_values = zip(*sorted_pairs)

    # Generate colors from a colormap
    colors = plt.cm.viridis(np.linspace(0, 1, len(filtered_labels)))


    # Plotting with filtered data and adjusted x-axis
    plt.figure(figsize=(12, 7))
    plt.bar(filtered_labels, filtered_values, color=colors)
    plt.title(f"Average Dependency Distances & Frequencies", fontsize=24, fontweight='medium')
    plt.xlabel("Distances in the Dependency Tree", fontsize=24, fontweight='medium')
    plt.ylabel("Average Frequency", fontsize=24, fontweight='medium')
    plt.tick_params(axis='both', which='major', labelsize=20)

    # Set x-ticks to show all distances
    plt.xticks(filtered_labels)
    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.show()

# Load the data from a tab-separated text file
data = pd.read_csv('/content/POS_data_relative20.txt', sep='\t', encoding='windows-1252')

# Display basic info about the data
print(f"Data shape: {data.shape}")
print(f"Columns: {list(data.columns)}")
print("\nFirst few rows of relevant columns:")
print(data[['EN_source', 'target_word', 'salient_words']].head(), "\n")

# Run function
avg_dependencies_distance(data)