# -*- coding: utf-8 -*-
"""model-annotations_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMhz58zL-Cngmwr4rIzjMnvSQxweTGON

Script to compare MT model saliency scores with human annotations

Annotations are taken from the work in [REDACTED for anonymity, will be added for the camera-ready version], which can be accessed [here].

# Access and process (human) annotations, saving to file for further comparison

1. Upload the mapped annotations JSON-MIN exports locally
"""

from google.colab import files

# Upload JSON file
uploaded = files.upload()

"""## Saving annotations for all JSON-MIN files per sentence into sheets in Excel, taking only majority label of annotations (simultaneously removes duplicates)

Define functions
"""

import spacy
import json
import pandas as pd
from collections import Counter

def load_json_files(filenames):
    """Load data from multiple files, keeping track of which file each entry came from"""
    all_data = {}
    for filename in filenames:
        filepath = f"/content/mapped_annotations_{filename}.json"
        with open(filepath, 'r', encoding='utf-8') as f:
            file_data = json.load(f)
            for entry in file_data:
                entry['filename'] = filename  # Add filename to each entry
            all_data[filename] = file_data
    return all_data


def extract_annotations_single(entry):
    """Extract annotations for a single entry and return DataFrame"""
    text = entry['text']
    word = entry['word']
    annotator = entry['annotator']
    filename = entry['filename']

    print(f"Filename: {filename}")
    print(f"Text: {text}")
    print(f"Word: {word}")

    # Check if label exists and is not empty
    if 'label' in entry and entry['label']:
        print("Annotations:")
        for label in entry['label']:
            annotated_text = label['text']
            start = label['start']
            end = label['end']
            label_tags = label['labels']
            print(f"  - Annotated Text: '{annotated_text}' (from {start} to {end}) with labels: {label_tags}")

        df_data = []

        for label in entry['label']:
            # Filter out empty strings from labels and get non-empty labels
            valid_labels = [str(lbl).strip() for lbl in label['labels'] if str(lbl).strip()]

            # Handle person word labels
            if entry['word'] == label['text'].strip():
                # This is the person word itself
                for lbl in valid_labels:
                    df_data.append({
                        'person_word': word,
                        'person_label': lbl,
                        'source_word': '',
                        'label': ''
                    })
            else:
                # Check if text is not empty after stripping
                stripped_text = label['text'].strip()

                # Only add if text is not empty and there are valid labels
                if stripped_text and valid_labels:
                    # Split stripped_text into individual words
                    split_words = stripped_text.split()

                    # Add each valid label × each word as a separate row
                    for lbl in valid_labels:
                        for part in split_words:
                            if part.lower() not in entry['word'].lower():
                                df_data.append({
                                    'person_word': word,  # Keep for grouping, but will be emptied later
                                    'person_label': '',
                                    'source_word': part.strip(".,:\"'—.-?![]()"),
                                    'label': lbl
                                })

        df = pd.DataFrame(df_data)

    else:
        print("No annotations for this entry.")
        df = pd.DataFrame(columns=['person_word', 'person_label', 'source_word', 'label'])  # Empty DataFrame

    print(df)
    print("\n" + "="*50 + "\n")

    return df


def get_majority_label(labels):
    """Get the majority label from a list of labels, excluding 'N/A'"""
    # Filter out 'N/A' values for majority calculation
    valid_labels = [label for label in labels if label.lower() not in ['n/a', 'na', '']]

    if not valid_labels:
        # If only N/A values, return the most common one (or just 'N/A')
        return Counter(labels).most_common(1)[0][0] if labels else 'N/A'

    # Return the most common valid label
    return Counter(valid_labels).most_common(1)[0][0]


def combine_with_majority_vote(combined_dfs):
    """Combine dataframes and select majority label for each Source_word and Person_word"""
    if not combined_dfs:
        return pd.DataFrame(columns=['person_word', 'person_label', 'source_word', 'label'])

    # Combine all dataframes
    all_data = pd.concat(combined_dfs, ignore_index=True)

    # Get the person word (should be the same across all entries for this sentence)
    person_word = all_data['person_word'].iloc[0] if not all_data.empty else ''

    # Group by person_word and collect all person labels
    person_labels = all_data[all_data['person_label'] != '']['person_label'].tolist()
    majority_person_label = get_majority_label(person_labels) if person_labels else ''

    print(f"  Person word: '{person_word}' - Labels: {person_labels} - Majority: '{majority_person_label}'")

    # Group by source_word and collect all labels
    source_data = all_data[all_data['source_word'] != '']
    grouped = source_data.groupby('source_word')['label'].apply(list).reset_index()

    # Build final data
    final_data = []

    # Add person word row first (only once)
    if person_word:
        final_data.append({
            'person_word': person_word,
            'person_label': majority_person_label,
            'source_word': '',
            'label': ''
        })

    # Calculate majority label for each Source_word (with empty person columns)
    for _, row in grouped.iterrows():
        source_word = row['source_word']
        labels = row['label']
        majority_label = get_majority_label(labels)

        print(f"  Source_word: '{source_word}' - Labels: {labels} - Majority: '{majority_label}'")

        final_data.append({
            'person_word': '',
            'person_label': '',
            'source_word': source_word,
            'label': majority_label
        })

    return pd.DataFrame(final_data)

"""Call data and functions"""

## Multiple files
filenames = ["000", "001", "002", "003", "004", "005", "006", "007", "008", "009",
             "010", "011", "012", "013", "014", "016", "018", "019", "020", "024", "026"] # Each ID refers to an annotator

# Load data from all specified files
all_data = load_json_files(filenames)

# Find the maximum number of entries across all files to determine how many sheets we need
max_entries = max(len(all_data[filename]) for filename in filenames)

# Modified main loop to collect dataframes and save to multi-sheet Excel
final_dataframes = []
sheet_names = []

# Process each sentence index across all files
for sentence_idx in range(max_entries):
    combined_dfs = []

    print(f"\n{'='*60}")
    print(f"PROCESSING SENTENCE {sentence_idx + 1}")
    print(f"{'='*60}")

    # For each file, get the annotations for this sentence index
    for filename in filenames:
        if sentence_idx < len(all_data[filename]):  # Check if this file has this sentence
            entry = all_data[filename][sentence_idx]
            df = extract_annotations_single(entry)
            if not df.empty:
                combined_dfs.append(df)
        else:
            print(f"Filename: {filename} - No data for sentence {sentence_idx + 1}")
            print("="*50)

    # Combine all dataframes for this sentence index with majority voting
    if combined_dfs:
        print(f"\nCALCULATING MAJORITY LABELS FOR SENTENCE {sentence_idx + 1}:")
        final_df = combine_with_majority_vote(combined_dfs)

        final_dataframes.append(final_df)
        sheet_names.append(f'Sent_{sentence_idx + 1}')

        print(f"\nCOMBINED RESULT FOR SENTENCE {sentence_idx + 1} (WITH MAJORITY VOTING):")
        print(final_df)
        print("="*60)


# Save all dataframes to different sheets in one Excel file
if final_dataframes:
    filename = f'Annotations_all_majority.xlsx'
    with pd.ExcelWriter(filename, engine='openpyxl') as writer:
        for df, sheet_name in zip(final_dataframes, sheet_names):
            df.to_excel(writer, sheet_name=sheet_name, index=False)

    print(f"\nSaved {len(final_dataframes)} dataframes to '{filename}'")
    print(f"Sheet names: {sheet_names}")
else:
    print("No dataframes to save - no annotations were found.")

"""## Same as previous function but including only annotations that were annotated by a minimum of two annotators (agreement)

Define Functions
"""

import json
import pandas as pd
from collections import Counter

def load_json_files(filenames):
    """Load data from multiple files, keeping track of which file each entry came from"""
    all_data = {}
    for filename in filenames:
        filepath = f"/content/mapped_annotations_{filename}.json"
        with open(filepath, 'r', encoding='utf-8') as f:
            file_data = json.load(f)
            for entry in file_data:
                entry['filename'] = filename  # Add filename to each entry
            all_data[filename] = file_data
    return all_data

def extract_annotations_single(entry):
    """Extract annotations for a single entry and return DataFrame"""
    text = entry['text']
    word = entry['word']
    annotator = entry['annotator']
    filename = entry['filename']

    print(f"Filename: {filename}")
    print(f"Text: {text}")
    print(f"Word: {word}")

    # Check if label exists and is not empty
    if 'label' in entry and entry['label']:
        print("Annotations:")
        for label in entry['label']:
            annotated_text = label['text']
            start = label['start']
            end = label['end']
            label_tags = label['labels']
            print(f"  - Annotated Text: '{annotated_text}' (from {start} to {end}) with labels: {label_tags}")

        df_data = []

        for label in entry['label']:
            # Filter out empty strings from labels and get non-empty labels
            valid_labels = [str(lbl).strip() for lbl in label['labels'] if str(lbl).strip()]

            # Handle person word labels
            if entry['word'] == label['text'].strip():
                # This is the person word itself
                for lbl in valid_labels:
                    df_data.append({
                        'person_word': word,
                        'person_label': lbl,
                        'source_word': '',
                        'label': ''
                    })
            else:
                # Check if text is not empty after stripping
                stripped_text = label['text'].strip()

                # Only add if text is not empty and there are valid labels
                if stripped_text and valid_labels:
                    # Split stripped_text into individual words
                    split_words = stripped_text.split()

                    # Add each valid label × each word as a separate row
                    for lbl in valid_labels:
                        for part in split_words:
                            if part.lower() not in entry['word'].lower():
                                df_data.append({
                                    'person_word': word,  # Keep for grouping, but will be emptied later
                                    'person_label': '',
                                    'source_word': part.strip(".,:\"'—.-?![]()"),
                                    'label': lbl
                                })

        df = pd.DataFrame(df_data)

    else:
        print("No annotations for this entry.")
        df = pd.DataFrame(columns=['person_word', 'person_label', 'source_word', 'label'])  # Empty DataFrame

    print(df)
    print("\n" + "="*50 + "\n")

    return df

def get_majority_label(labels):
    """Get the majority label from a list of labels, excluding 'N/A'"""
    # Filter out 'N/A' values for majority calculation
    valid_labels = [label for label in labels if label.lower() not in ['n/a', 'na', '']]

    if not valid_labels:
        # If only N/A values, return the most common one (or just 'N/A')
        return Counter(labels).most_common(1)[0][0] if labels else 'N/A'

    # Return the most common valid label
    return Counter(valid_labels).most_common(1)[0][0]

def combine_with_majority_vote(combined_dfs):
    """Combine dataframes and select majority label for each Source_word and Person_word"""
    if not combined_dfs:
        return pd.DataFrame(columns=['person_word', 'person_label', 'source_word', 'label'])

    # Combine all dataframes
    all_data = pd.concat(combined_dfs, ignore_index=True)

    # Get the person word (should be the same across all entries for this sentence)
    person_word = all_data['person_word'].iloc[0] if not all_data.empty else ''

    # Group by person_word and collect all person labels
    person_labels = all_data[all_data['person_label'] != '']['person_label'].tolist()
    majority_person_label = get_majority_label(person_labels) if person_labels else ''

    print(f"  Person word: '{person_word}' - Labels: {person_labels} - Majority: '{majority_person_label}'")

    # Group by source_word and collect all labels
    source_data = all_data[all_data['source_word'] != '']
    grouped = source_data.groupby('source_word')['label'].apply(list).reset_index()

    # Build final data
    final_data = []

    # Add person word row first (only once)
    if person_word:
        final_data.append({
            'person_word': person_word,
            'person_label': majority_person_label,
            'source_word': '',
            'label': ''
        })

    # Calculate majority label for each Source_word (with empty person columns)
    for _, row in grouped.iterrows():
        source_word = row['source_word']
        labels = row['label']
        majority_label = get_majority_label(labels)

        print(f"  Source_word: '{source_word}' - Labels: {labels} - Majority: '{majority_label}'")

        final_data.append({
            'person_word': '',
            'person_label': '',
            'source_word': source_word,
            'label': majority_label
        })

    return pd.DataFrame(final_data)

"""Call data and function"""

## Multiple files
filenames = ["000", "001", "002", "003", "004", "005", "006", "007", "008", "009",
             "010", "011", "012", "013", "014", "016", "018", "019", "020", "024", "026"]

# Load data from all specified files
all_data = load_json_files(filenames)

# Find the maximum number of entries across all files to determine how many sheets we need
max_entries = max(len(all_data[filename]) for filename in filenames)

# Modified main loop to collect dataframes and save to multi-sheet Excel
final_dataframes = []
sheet_names = []

# Process each sentence index across all files
for sentence_idx in range(max_entries):
    combined_dfs = []

    print(f"\n{'='*60}")
    print(f"PROCESSING SENTENCE {sentence_idx + 1}")
    print(f"{'='*60}")

    # For each file, get the annotations for this sentence index
    for filename in filenames:
        if sentence_idx < len(all_data[filename]):  # Check if this file has this sentence
            entry = all_data[filename][sentence_idx]
            df = extract_annotations_single(entry)
            if not df.empty:
                combined_dfs.append(df)
        else:
            print(f"Filename: {filename} - No data for sentence {sentence_idx + 1}")
            print("="*50)

    # Combine all dataframes for this sentence index with majority voting
    if combined_dfs:
        print(f"\nCALCULATING MAJORITY LABELS FOR SENTENCE {sentence_idx + 1}:")
        final_df = combine_with_majority_vote(combined_dfs)

        final_dataframes.append(final_df)
        sheet_names.append(f'Sent_{sentence_idx + 1}')

        print(f"\nCOMBINED RESULT FOR SENTENCE {sentence_idx + 1} (WITH MAJORITY VOTING):")
        print(final_df)
        print("="*60)

# Save all dataframes to different sheets in one Excel file
if final_dataframes:
    filename = f'Annotations_all_majority.xlsx'
    with pd.ExcelWriter(filename, engine='openpyxl') as writer:
        for df, sheet_name in zip(final_dataframes, sheet_names):
            df.to_excel(writer, sheet_name=sheet_name, index=False)

    print(f"\nSaved {len(final_dataframes)} dataframes to '{filename}'")
    print(f"Sheet names: {sheet_names}")
else:
    print("No dataframes to save - no annotations were found.")

"""# Compare saliency scores with annotations

Import Excel files with saliency attribution scores, if not saved from above.
"""

from google.colab import files

# Upload JSON file
uploaded = files.upload()

"""## Define functions to compare annotations to attribution scores

This function computes the overall comparison of attribution scores (Excel file with normalised attribution scores from notebook ``saliency_analysis_contrastive_gender.py``) also found in annotations (Excel file created at top of this notebook.)
"""

import pandas as pd

def complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage):
    """
    Analyse overlap between attribution scores and annotations across all sheets (from imported Excel files).

    Parameters:
    - attribution_scores: Dictionary of DataFrames from Excel sheets
    - annotations: Dictionary of DataFrames from Excel sheets
    - top_percentage: Float representing the top percentage of attribution scores (e.g. top 25% or top 10%)

    Returns:
    - summary_df: DataFrame containing summary statistics for all sentences
    """


    # Dictionary to store overlapping data for each sheet
    overlapping_data = {}

    # Get all possible sheet names from both files to ensure we process all sentences
    all_sheet_names = set(attribution_scores.keys()).union(set(annotations.keys()))

    # Compare each sheet
    for sheet_name in sorted(all_sheet_names):  # Sort to maintain consistent order
        #print(f"\nProcessing sheet: {sheet_name}")

        # Check if sheets exist in both files
        attr_exists = sheet_name in attribution_scores
        annot_exists = sheet_name in annotations

        if attr_exists and annot_exists:
            attr_df = attribution_scores[sheet_name]
            annot_df = annotations[sheet_name]

            # Check if 'Source_word' column exists in both dataframes
            if 'Source_word' in attr_df.columns and 'Source_word' in annot_df.columns:
                # Get unique values from each Source_word column
                attr_words = set(attr_df['Source_word'].dropna())
                annot_words = set(annot_df['Source_word'].dropna())

                # Find overlapping words
                overlapping_words = attr_words.intersection(annot_words)

                if overlapping_words:
                    #print(f"  Found {len(overlapping_words)} overlapping words: {overlapping_words}")

                    # Filter rows from attribution_scores where Source_word overlaps
                    attr_overlapping = attr_df[attr_df['Source_word'].isin(overlapping_words)]

                    # Filter rows from annotations where Source_word overlaps
                    annot_overlapping = annot_df[annot_df['Source_word'].isin(overlapping_words)]

                    # Create combined dataframe with overlapping data
                    # Add a column to identify the source file
                    attr_overlapping_copy = attr_overlapping.copy()
                    attr_overlapping_copy['Source_file'] = 'Attribution_Scores'

                    annot_overlapping_copy = annot_overlapping.copy()
                    annot_overlapping_copy['Source_file'] = 'Annotations'

                    # Combine both dataframes
                    combined_overlapping = pd.concat([attr_overlapping_copy, annot_overlapping_copy],
                                                  ignore_index=True, sort=False)

                    # Store in dictionary
                    overlapping_data[sheet_name] = combined_overlapping

                    #print(f"  Combined overlapping data shape: {combined_overlapping.shape}")
                    #print(f"  Columns in combined data: {combined_overlapping.columns.tolist()}")

                else:
                    # Create empty dataframe with all possible columns from both sources
                    all_columns = set()
                    if not attr_df.empty:
                        all_columns.update(attr_df.columns)
                    if not annot_df.empty:
                        all_columns.update(annot_df.columns)
                    all_columns.add('Source_file')  # Add the source file column

                    # Create empty dataframe with all columns
                    empty_df = pd.DataFrame(columns=list(all_columns))
                    overlapping_data[sheet_name] = empty_df

            else:
                # Create empty dataframe
                empty_df = pd.DataFrame(columns=['Source_word', 'Source_file'])
                overlapping_data[sheet_name] = empty_df

        elif attr_exists and not annot_exists:
            # Create empty dataframe with attribution columns plus Source_file
            attr_df = attribution_scores[sheet_name]
            columns = list(attr_df.columns) + ['Source_file']
            empty_df = pd.DataFrame(columns=columns)
            overlapping_data[sheet_name] = empty_df

        elif not attr_exists and annot_exists:
            # Create empty dataframe with annotation columns plus Source_file
            annot_df = annotations[sheet_name]
            columns = list(annot_df.columns) + ['Source_file']
            empty_df = pd.DataFrame(columns=columns)
            overlapping_data[sheet_name] = empty_df


    # Save overlapping data to new Excel file (including empty sheets)
    if overlapping_data:
        output_filename = f'Complete_overlap_analysis_attribution_and_annotation_{top_percentage}.xlsx'
        with pd.ExcelWriter(output_filename, engine='openpyxl') as writer:
            for sheet_name, df in overlapping_data.items():
                df.to_excel(writer, sheet_name=sheet_name, index=False)

    # Create a comprehensive summary report for ALL sentences
    summary_data_complete = []
    for sheet_name in sorted(all_sheet_names):
        attr_total = len(attribution_scores[sheet_name]) if sheet_name in attribution_scores else 0
        annot_total = len(annotations[sheet_name]) if sheet_name in annotations else 0
        overlapping_rows = len(overlapping_data[sheet_name]) if sheet_name in overlapping_data else 0
        unique_overlapping_words = overlapping_data[sheet_name]['Source_word'].nunique() if sheet_name in overlapping_data and len(overlapping_data[sheet_name]) > 0 else 0

        # Calculate percentage based on attribution_scores if it exists, otherwise use annotations
        if attr_total > 0:
            overlap_percentage = (unique_overlapping_words / attr_total) * 100
        elif annot_total > 0:
            overlap_percentage = (unique_overlapping_words / annot_total) * 100
        else:
            overlap_percentage = 0

        summary_data_complete.append({
            'Sheet': sheet_name,
            'Attribution_Total': attr_total,
            'Annotations_Total': annot_total,
            'Overlapping_Rows': overlapping_rows,
            'Unique_Overlapping_Words': unique_overlapping_words,
            '% Overlapping': round(overlap_percentage, 2)
        })


    # Create and save summary report
    summary_df_complete = pd.DataFrame(summary_data_complete)
    #print(f"\nCOMPLETE SUMMARY REPORT (ALL {len(summary_df_complete)} SENTENCES):")
    #print(summary_df_complete)

    # Save summary to Excel
    summary_filename = f'Summary_overlap_analysis_{top_percentage}.xlsx'
    summary_df_complete.to_excel(summary_filename, index=False)
    print(f"\nSaved summary report to '{summary_filename}'")

    # Additional statistics
    total_sentences_with_overlap = len([row for row in summary_data_complete if row['Unique_Overlapping_Words'] > 0])
    total_sentences_without_overlap = len(summary_data_complete) - total_sentences_with_overlap

    print(f"\nSTATISTICS:")
    print(f"Total sentences processed: {len(summary_df_complete)}")
    print(f"Sentences with overlap: {total_sentences_with_overlap}")
    print(f"Sentences without overlap: {total_sentences_without_overlap}")
    print(f"Average overlap percentage: {summary_df_complete['% Overlapping'].mean():.2f}%")

    # Return the DataFrame instead of the list
    return summary_df_complete

"""Now you can run the first function, computing the overlap and saving to Excel. It returns a dataframe with overlap results.

You have to define the two input Excel files for both attribution scores and annotations as well as define the top_percentage that you are looking at (based on attribution scores).

### For ALL annotators

APPROACH 1: TOP % of all words
"""

for top_percentage in [0.05, 0.1, 0.15, 0.2, 0.25]:

  if __name__ == "__main__":
      print(f"Comparison to top percentage of: {top_percentage}")
      # Load the data
      attribution_scores = pd.read_excel(f'Normalised_attribution_fullyEdited_scores_{top_percentage}_exclStopwords.xlsx', sheet_name=None)
      #top_percentage = 0.2
      annotations = pd.read_excel('Annotations_all_majority.xlsx', sheet_name=None)

      # Call the function and capture the returned DataFrame
      summary_results = complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage)

      # Now you can use summary_results as a DataFrame for further analysis
      print("DataFrame returned successfully!\n")

"""APPROACH 2: TOP 1 word"""

if __name__ == "__main__":
    print(f"Comparison to top one word.")
    # Load the data
    attribution_scores = pd.read_excel(f'Normalised_attribution_fullyEdited_top_word_exclStopwords.xlsx', sheet_name=None)
    annotations = pd.read_excel('Annotations_all_majority.xlsx', sheet_name=None)

    # Call the function and capture the returned DataFrame
    summary_results = complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage)

    # Now you can use summary_results as a DataFrame for further analysis
    print("DataFrame returned successfully!\n")

"""APPROACH 3: WORDS WITH A MIN. ATTRIBUTION SCORE OF X"""

for top_percentage in [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]:

  if __name__ == "__main__":
      print(f"Comparison to words with a min. attribution score of: {top_percentage}")
      # Load the data
      attribution_scores = pd.read_excel(f'Normalised_attribution_fullyEdited_minimum_score_of_{top_percentage}_exclStopwords.xlsx', sheet_name=None)
      annotations = pd.read_excel('Annotations_all_majority.xlsx', sheet_name=None)

      # Call the function and capture the returned DataFrame
      summary_results = complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage)

      # Now you can use summary_results as a DataFrame for further analysis
      print("DataFrame returned successfully!\n")

"""APPROACH 4: TOP % relative to scores sum per individual sentence."""

for top_percentage in [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]:

  if __name__ == "__main__":
      print(f"Comparison to words summed/relative to attribution scores of: {top_percentage}")
      # Load the data
      attribution_scores = pd.read_excel(f'Normalised_attribution_fullyEdited_scores_sums_per_sentence_top_{top_percentage}_exclStopwords.xlsx', sheet_name=None)
      annotations = pd.read_excel('Annotations_all_majority.xlsx', sheet_name=None)

      # Call the function and capture the returned DataFrame
      summary_results = complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage)

      # Now you can use summary_results as a DataFrame for further analysis
      print("DataFrame returned successfully!\n")

"""### For min. 2 agree Annotators

APPROACH 1
"""

for top_percentage in [0.05, 0.1, 0.15, 0.2, 0.25]:

  if __name__ == "__main__":
      print(f"Comparison to top percentage of: {top_percentage}")
      # Load the data
      attribution_scores = pd.read_excel(f'Normalised_attribution_fullyEdited_scores_{top_percentage}_exclStopwords.xlsx', sheet_name=None)
      annotations = pd.read_excel('All_annotations_duplicates_removed_majority_min_two_agree.xlsx', sheet_name=None)

      # Call the function and capture the returned DataFrame
      summary_results = complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage)

      # Now you can use summary_results as a DataFrame for further analysis
      print("DataFrame returned successfully!\n")

"""APPROACH 2"""

if __name__ == "__main__":
    print(f"Comparison to top one word.")
    # Load the data
    attribution_scores = pd.read_excel(f'Normalised_attribution_fullyEdited_top_word_exclStopwords.xlsx', sheet_name=None)
    annotations = pd.read_excel('All_annotations_duplicates_removed_majority_min_two_agree.xlsx', sheet_name=None)

    # Call the function and capture the returned DataFrame
    summary_results = complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage)

    # Now you can use summary_results as a DataFrame for further analysis
    print("DataFrame returned successfully!\n")

"""APPROACH 3"""

for top_percentage in [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]:

  if __name__ == "__main__":
      print(f"Comparison to words with a min. attribution score of: {top_percentage}")
      # Load the data
      attribution_scores = pd.read_excel(f'Normalised_attribution_fullyEdited_minimum_score_of_{top_percentage}_exclStopwords.xlsx', sheet_name=None)
      annotations = pd.read_excel('All_annotations_duplicates_removed_majority_min_two_agree.xlsx', sheet_name=None)

      # Call the function and capture the returned DataFrame
      summary_results = complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage)

      # Now you can use summary_results as a DataFrame for further analysis
      print("DataFrame returned successfully!\n")

"""APPROACH 4"""

for top_percentage in [0.2]: #[0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]:

  if __name__ == "__main__":
      print(f"Comparison to words summed/relative to attribution scores of: {top_percentage}")
      # Load the data
      attribution_scores = pd.read_excel(f'Normalised_attribution_fullyEdited_scores_sums_per_sentence_top_{top_percentage}_exclStopwords.xlsx', sheet_name=None)
      annotations = pd.read_excel('All_annotations_duplicates_removed_majority_min_two_agree.xlsx', sheet_name=None)

      # Call the function and capture the returned DataFrame
      summary_results = complete_overlap_analysis_attribution_and_annotation(attribution_scores, annotations, top_percentage)

      # Now you can use summary_results as a DataFrame for further analysis
      print("DataFrame returned successfully!\n")

"""# Visualise Charts

## Model-Human Comparison: All Annotators
"""

# APPROACH 1
top_percentage_dict = {"5": 81.67, "10": 81.11, "15": 80.36, "20": 78.04, "25": 77.47}
top_percentage = {"10": 81.11}

# APPROACH 2
top_one_word = {"1": 81.67}

# APPROACH 3
min_score_dict = {"0.01": 56.17, "0.02": 62.53, "0.03": 66.87, "0.04": 74.12, "0.05": 78.05, "0.06": 78.72, "0.07": 78.42, "0.08": 72.92, "0.09": 64.17, "0.1": 63.89}
top_percentage = {"0.06": 78.72}

# APPROACH 4
top_relative_percentage_dict = {"5": 81.67, "10": 81.67, "15": 80.83, "20": 83.33, "25": 81.67, "30": 80.56, "35": 79.03, "40": 79.50, "45": 76.98, "50": 75.33}
top_percentage = {"20": 83.33}


## TOP SCORES COMBINED
top_scores_per_approach = {"1": 81.11, "2": 81.67, "3": 78.72, "4": 83.33}

import matplotlib.pyplot as plt
import numpy as np

# Data
data_dict = top_scores_per_approach

# Extract x and y values
x_values = list(data_dict.keys())
y_values = list(data_dict.values())

average_overlap = np.mean(y_values)

# Create the bar chart
plt.figure(figsize=(10, 6))
bars = plt.bar(x_values, y_values, color='#3b82f6', alpha=0.8, edgecolor='#1e40af', linewidth=1.5)

# Customize the chart
plt.title('Highest Model-Human Overlap % per Approach',
          fontsize=20, fontweight='medium', pad=20)
plt.xlabel('Approach', fontsize=20, fontweight='medium')
plt.ylabel('Overlap (%)', fontsize=20, fontweight='medium')

plt.tick_params(axis='both', which='major', labelsize=18)

# Add average line
plt.axhline(y=average_overlap, color='green', linestyle='--',
            linewidth=2, alpha=0.7, label=f'Average ({average_overlap:.1f}%)')

# Add legend
plt.legend(loc='upper right', frameon=True, fancybox=True, shadow=True, fontsize=18)


# Set y-axis limits for better visualization
plt.ylim(70, 90)

# Add value labels on top of each bar
for bar, value in zip(bars, y_values):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
             f'{value}%', ha='center', va='bottom', fontsize=20, fontweight='bold')

# Add grid for better readability
plt.grid(axis='y', alpha=0.3, linestyle='--')

# Customize appearance
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['left'].set_color('#cccccc')
plt.gca().spines['bottom'].set_color('#cccccc')

# Adjust layout and display
plt.tight_layout()
plt.show()

# Optional: Save the figure
# plt.savefig('trigger_words_overlap_chart.png', dpi=300, bbox_inches='tight')

# Print summary statistics
print("\nData Summary:")
print("-" * 40)
for score, percentage in data_dict.items():
    print(f"Score {score}: {percentage}%")

print(f"\nPeak Performance: {max(y_values)}% at score {x_values[y_values.index(max(y_values))]}")
print(f"Lowest Performance: {min(y_values)}% at score {x_values[y_values.index(min(y_values))]}")
print(f"Range: {min(y_values)}% - {max(y_values)}% ({max(y_values) - min(y_values)} percentage point spread)")

import matplotlib.pyplot as plt
import numpy as np

# Data
sum_dict = top_relative_percentage_dict

# Extract thresholds and values
thresholds = list(sum_dict.keys())
values = list(sum_dict.values())

# Calculate average overlap
average_overlap = np.mean(values)

# Set up the bar chart
x = np.arange(len(thresholds))
width = 0.6

# Color gradient from red to purple
colors = ['#e11d48', '#f97316', '#eab308', '#22c55e', '#06b6d4',
          '#3b82f6', '#8b5cf6', '#ec4899', '#64748b', '#a855f7']

fig, ax = plt.subplots(figsize=(14, 8))

# Create bars
bars = ax.bar(x, values, width, color=colors, alpha=0.8,
              edgecolor='black', linewidth=1.5)

# Customize the chart
plt.title('Model-Human Overlap % for Approach 4',
          fontsize=30, fontweight='medium', pad=20)
ax.set_xlabel('Top % of attribution scores summed relative per sentence', fontsize=26, fontweight='medium')
ax.set_ylabel('Overlap (%)', fontsize=26, fontweight='medium')

plt.tick_params(axis='both', which='major', labelsize=26)

# Set y-axis limits for better visualization
ax.set_ylim(70, 85)

# Set x-axis with larger font
ax.set_xticks(x)
ax.set_xticklabels(thresholds, fontsize=26)

# Add average line
plt.axhline(y=average_overlap, color='green', linestyle='--',
            linewidth=2, alpha=0.7, label=f'Average ({average_overlap:.1f}%)')

# Add legend
plt.legend(loc='upper right', frameon=True, fancybox=True, shadow=True, fontsize=26)

# Add value labels on top of each bar with larger font
for bar in bars:
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 0.5,
            f'{height:.2f}', ha='center', va='bottom', fontsize=24, fontweight='bold')

# Add grid for better readability
ax.grid(axis='y', alpha=0.3, linestyle='--')

# Customize appearance
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color('#cccccc')
ax.spines['bottom'].set_color('#cccccc')

# Adjust layout and display
plt.tight_layout()
plt.show()

# Optional: Save the figure
# plt.savefig('trigger_words_overlap_chart.png', dpi=300, bbox_inches='tight')

# Print summary statistics
print("\nData Summary:")
print("-" * 60)
for threshold, value in sum_dict.items():
    print(f"Threshold {threshold}: {value}%")

# Find peak performance
max_value = max(values)
min_value = min(values)
max_threshold = thresholds[values.index(max_value)]
min_threshold = thresholds[values.index(min_value)]

print(f"\nPeak Performance: {max_value}% at threshold {max_threshold}")
print(f"Lowest Performance: {min_value}% at threshold {min_threshold}")
print(f"Range: {min_value}% - {max_value}% ({max_value - min_value:.2f} point spread)")
print(f"Average Performance: {np.mean(values):.2f}%")

import matplotlib.pyplot as plt
import numpy as np

# Data
sum_dict = min_score_dict

# Extract thresholds and values
thresholds = list(sum_dict.keys())
values = list(sum_dict.values())

# Calculate average overlap
average_overlap = np.mean(values)

# Set up the bar chart
x = np.arange(len(thresholds))
width = 0.6

# Color gradient from red to purple
colors = ['#e11d48', '#f97316', '#eab308', '#22c55e', '#06b6d4',
          '#3b82f6', '#8b5cf6', '#ec4899', '#64748b', '#a855f7']

fig, ax = plt.subplots(figsize=(14, 8))

# Create bars
bars = ax.bar(x, values, width, color=colors, alpha=0.8,
              edgecolor='black', linewidth=1.5)

# Customize the chart
plt.title('Model-Human Overlap % for Approach 3',
          fontsize=30, fontweight='medium', pad=20)
ax.set_xlabel('Min. value of attribution score per word', fontsize=30, fontweight='medium')
ax.set_ylabel('Overlap (%)', fontsize=26, fontweight='medium')

plt.tick_params(axis='both', which='major', labelsize=26)

# Set y-axis limits for better visualization
ax.set_ylim(55, 85)

# Set x-axis with larger font
ax.set_xticks(x)
ax.set_xticklabels(thresholds, fontsize=26)

# Add average line
plt.axhline(y=average_overlap, color='green', linestyle='--',
            linewidth=2, alpha=0.7, label=f'Average ({average_overlap:.1f}%)')

# Add legend
plt.legend(loc='upper right', frameon=True, fancybox=True, shadow=True, fontsize=26)

# Add value labels on top of each bar with larger font
for bar in bars:
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 0.5,
            f'{height:.2f}', ha='center', va='bottom', fontsize=24, fontweight='bold')

# Add grid for better readability
ax.grid(axis='y', alpha=0.3, linestyle='--')

# Customize appearance
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color('#cccccc')
ax.spines['bottom'].set_color('#cccccc')

# Adjust layout and display
plt.tight_layout()
plt.show()

# Optional: Save the figure
# plt.savefig('trigger_words_overlap_chart.png', dpi=300, bbox_inches='tight')

# Print summary statistics
print("\nData Summary:")
print("-" * 60)
for threshold, value in sum_dict.items():
    print(f"Threshold {threshold}: {value}%")

# Find peak performance
max_value = max(values)
min_value = min(values)
max_threshold = thresholds[values.index(max_value)]
min_threshold = thresholds[values.index(min_value)]

print(f"\nPeak Performance: {max_value}% at threshold {max_threshold}")
print(f"Lowest Performance: {min_value}% at threshold {min_threshold}")
print(f"Range: {min_value}% - {max_value}% ({max_value - min_value:.2f} point spread)")
print(f"Average Performance: {np.mean(values):.2f}%")

import matplotlib.pyplot as plt
import numpy as np

# Data
sum_dict = top_percentage_dict

# Extract thresholds and values
thresholds = list(sum_dict.keys())
values = list(sum_dict.values())

# Calculate average overlap
average_overlap = np.mean(values)

# Set up the bar chart
x = np.arange(len(thresholds))
width = 0.6

# Color gradient from red to purple
colors = ['#e11d48', '#f97316', '#eab308', '#22c55e', '#06b6d4',
          '#3b82f6', '#8b5cf6', '#ec4899', '#64748b', '#a855f7']

fig, ax = plt.subplots(figsize=(14, 8))

# Create bars
bars = ax.bar(x, values, width, color=colors, alpha=0.8,
              edgecolor='black', linewidth=1.5)

# Customize the chart
plt.title('Model-Human Overlap % for Approach 1',
          fontsize=30, fontweight='medium', pad=20)
ax.set_xlabel('Top % of source words', fontsize=30, fontweight='medium')
ax.set_ylabel('Overlap (%)', fontsize=30, fontweight='medium')

plt.tick_params(axis='both', which='major', labelsize=26)

# Set y-axis limits for better visualization
ax.set_ylim(75, 85)

# Set x-axis with larger font
ax.set_xticks(x)
ax.set_xticklabels(thresholds, fontsize=26)

# Add average line
plt.axhline(y=average_overlap, color='green', linestyle='--',
            linewidth=2, alpha=0.7, label=f'Average ({average_overlap:.1f}%)')

# Add legend
plt.legend(loc='upper right', frameon=True, fancybox=True, shadow=True, fontsize=26)

# Add value labels on top of each bar with larger font
for bar in bars:
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 0.5,
            f'{height:.2f}', ha='center', va='bottom', fontsize=24, fontweight='bold')

# Add grid for better readability
ax.grid(axis='y', alpha=0.3, linestyle='--')

# Customize appearance
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color('#cccccc')
ax.spines['bottom'].set_color('#cccccc')

# Adjust layout and display
plt.tight_layout()
plt.show()

# Optional: Save the figure
# plt.savefig('trigger_words_overlap_chart.png', dpi=300, bbox_inches='tight')

# Print summary statistics
print("\nData Summary:")
print("-" * 60)
for threshold, value in sum_dict.items():
    print(f"Threshold {threshold}: {value}%")

# Find peak performance
max_value = max(values)
min_value = min(values)
max_threshold = thresholds[values.index(max_value)]
min_threshold = thresholds[values.index(min_value)]

print(f"\nPeak Performance: {max_value}% at threshold {max_threshold}")
print(f"Lowest Performance: {min_value}% at threshold {min_threshold}")
print(f"Range: {min_value}% - {max_value}% ({max_value - min_value:.2f} point spread)")
print(f"Average Performance: {np.mean(values):.2f}%")

"""## Model-Human Comparison: For All Annotators & where Min 2 Agree

"""

# APPROACH 1
top_percentage_dict_comparison = {
    "5": {"All (min. 2 agree)": 66.67, "All": 81.67},
    "10": {"All (min. 2 agree)": 65.00, "All": 81.11},
    "15": {"All (min. 2 agree)": 66.42, "All": 80.36},
    "20": {"All (min. 2 agree)": 64.54, "All": 78.04},
    "25": {"All (min. 2 agree)": 61.41, "All": 77.47}}

# APPROACH 2
top_one_word = {"All (min. 2 agree)": 66.67, "All": 81.67}

# APPROACH 3
min_score_dict_comparison = {
    "0.01": {"All (min. 2 agree)": 42.45, "All": 56.17},
    "0.02": {"All (min. 2 agree)": 49.20, "All": 62.53},
    "0.03": {"All (min. 2 agree)": 53.86, "All": 66.87},
    "0.04": {"All (min. 2 agree)": 59.73, "All": 74.12},
    "0.05": {"All (min. 2 agree)": 65.79, "All": 78.05},
    "0.06": {"All (min. 2 agree)": 68.28, "All": 78.72},
    "0.07": {"All (min. 2 agree)": 69.06, "All": 78.42},
    "0.08": {"All (min. 2 agree)": 64.31, "All": 72.92},
    "0.09": {"All (min. 2 agree)": 54.72, "All": 64.17},
    "0.1": {"All (min. 2 agree)": 52.50, "All": 63.89}}

# APPROACH 4
top_relative_percentage_dict_comparison = {
    "5": {"All (min. 2 agree)": 66.67, "All": 81.67},
    "10": {"All (min. 2 agree)": 66.67, "All": 81.67},
    "15": {"All (min. 2 agree)": 65.83, "All": 80.83},
    "20": {"All (min. 2 agree)": 68.33, "All": 83.33},
    "25": {"All (min. 2 agree)": 68.06, "All": 81.67},
    "30": {"All (min. 2 agree)": 65.14, "All": 80.56},
    "35": {"All (min. 2 agree)": 63.83, "All": 79.03},
    "40": {"All (min. 2 agree)": 64.28, "All": 79.50},
    "45": {"All (min. 2 agree)": 62.16, "All": 76.98},
    "50": {"All (min. 2 agree)": 61.11, "All": 75.33}}


## TOP SCORES COMBINED
top_scores_per_approach = {"1": 81.11, "2": 81.67, "3": 78.72, "4": 83.33}

import numpy as np

# Extract values for each category
min_2_agree_values = [data["All (min. 2 agree)"] for data in top_relative_percentage_dict_comparison.values()]
all_values = [data["All"] for data in top_relative_percentage_dict_comparison.values()]

# Calculate statistics
min_2_agree_mean = np.mean(min_2_agree_values)
min_2_agree_std = np.std(min_2_agree_values, ddof=1)  # ddof=1 for sample std deviation

all_mean = np.mean(all_values)
all_std = np.std(all_values, ddof=1)

# Print results
print("=== STATISTICS ===")
print(f"\nAll (min. 2 agree):")
print(f"  Mean: {min_2_agree_mean:.2f}%")
print(f"  Std Dev: {min_2_agree_std:.2f}%")

print(f"\nAll:")
print(f"  Mean: {all_mean:.2f}%")
print(f"  Std Dev: {all_std:.2f}%")

import matplotlib.pyplot as plt
import numpy as np

# Data (fixed syntax)
sum_dict = top_relative_percentage_dict_comparison

# Extract data for grouped bar chart
categories = list(sum_dict["10"].keys())
sum_005 = list(sum_dict["5"].values())
sum_01 = list(sum_dict["10"].values())
sum_015 = list(sum_dict["15"].values())
sum_02 = list(sum_dict["20"].values())
sum_025 = list(sum_dict["25"].values())
sum_03 = list(sum_dict["30"].values())
sum_035 = list(sum_dict["35"].values())
sum_04 = list(sum_dict["40"].values())
sum_045 = list(sum_dict["45"].values())
sum_05 = list(sum_dict["50"].values())

# Set up the bar chart
x = np.arange(len(categories))  # Label locations
width = 0.09  # Width of bars (narrower to fit 9 groups)

fig, ax = plt.subplots(figsize=(16, 10))

# Create bars with proper positioning and 9 different colors
bars1 = ax.bar(x - 4*width, sum_005, width, label='5',
               color='#e11d48', alpha=0.8, edgecolor='#be185d', linewidth=1.5)
bars2 = ax.bar(x - 3*width, sum_01, width, label='10',
               color='#f97316', alpha=0.8, edgecolor='#ea580c', linewidth=1.5)
bars3 = ax.bar(x - 2*width, sum_015, width, label='15',
               color='#eab308', alpha=0.8, edgecolor='#ca8a04', linewidth=1.5)
bars4 = ax.bar(x - width, sum_02, width, label='20',
               color='#22c55e', alpha=0.8, edgecolor='#16a34a', linewidth=1.5)
bars5 = ax.bar(x, sum_025, width, label='25',
               color='#06b6d4', alpha=0.8, edgecolor='#0891b2', linewidth=1.5)
bars6 = ax.bar(x + width, sum_03, width, label='30',
               color='#3b82f6', alpha=0.8, edgecolor='#2563eb', linewidth=1.5)
bars7 = ax.bar(x + 2*width, sum_035, width, label='35',
               color='#8b5cf6', alpha=0.8, edgecolor='#7c3aed', linewidth=1.5)
bars8 = ax.bar(x + 3*width, sum_04, width, label='40',
               color='#ec4899', alpha=0.8, edgecolor='#db2777', linewidth=1.5)
bars9 = ax.bar(x + 4*width, sum_045, width, label='45',
               color='#64748b', alpha=0.8, edgecolor='#475569', linewidth=1.5)
bars10 = ax.bar(x + 5*width, sum_05, width, label='50',
               color='#a855f7', alpha=0.8, edgecolor='#9333ea', linewidth=1.5)

# Customize the chart
ax.set_title('Model-Human Overlap Approach 4: All Annotators vs. Min. 2 Agree',
             fontsize=30, fontweight='medium', pad=20)
ax.set_xlabel('Annotation Selection', fontsize=30, fontweight='medium')
ax.set_ylabel('Overlap (%)', fontsize=30, fontweight='medium')

plt.tick_params(axis='both', which='major', labelsize=30)

# Set y-axis limits for better visualization
ax.set_ylim(60, 85)

# Set x-axis
ax.set_xticks(x)
ax.set_xticklabels(categories, fontsize=30)


# Add legend
ax.legend(loc='upper left', bbox_to_anchor=(0.02, 0.98), ncol=2, fontsize=26)

# Add grid for better readability
ax.grid(axis='y', alpha=0.3, linestyle='--')

# Customize appearance
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color('#cccccc')
ax.spines['bottom'].set_color('#cccccc')

# Adjust layout and display
plt.tight_layout()
plt.show()

# Optional: Save the figure
# plt.savefig('trigger_words_overlap_grouped_chart.png', dpi=300, bbox_inches='tight')

# Print summary statistics
print("\nData Summary:")
print("-" * 60)
for sum, data in sum_dict.items():
    print(f"\n{sum} Top Sum:")
    for category, value in data.items():
        print(f"  {category}: {value}%")

# Find overall peak performance
all_values = []
all_labels = []
for sum, data in sum_dict.items():
    for cat, val in data.items():
        all_values.append(val)
        all_labels.append(f"{cat} ({sum})")

max_idx = all_values.index(max(all_values))
min_idx = all_values.index(min(all_values))

print(f"\nOverall Peak Performance: {max(all_values)}% - {all_labels[max_idx]}")
print(f"Overall Lowest Performance: {min(all_values)}% - {all_labels[min_idx]}")
print(f"Overall Range: {min(all_values)}% - {max(all_values)}% ({max(all_values) - min(all_values)} point spread)")

# Performance analysis across thresholds
print(f"\nPerformance Trends by Category:")
print("-" * 40)
for category in categories:
    values = [sum_dict[sum][category] for sum in ["5", "10", "15", "20", "25", "30", "35", "40", "45", "50"]]
    best_sum = ["5", "10", "15", "20", "25", "30", "35", "40", "45", "50"][values.index(max(values))]
    worst_sum = ["5", "10", "15", "20", "25", "30", "35", "40", "45", "50"][values.index(min(values))]
    improvement = max(values) - min(values)

    print(f"{category}:")
    print(f"  Best: {max(values)}% at {best_sum}")
    print(f"  Worst: {min(values)}% at {worst_sum}")
    print(f"  Improvement range: {improvement}%")
    print()