# -*- coding: utf-8 -*-
"""saliency_analysis_contrastive-gender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zWD2MXV4YuMC0h8i4M9-fRGHI0fEJA8L

# Computing Saliency Attribution for Gender-Contrastive Translations

# Install inseq requirements
"""

!python --version

pip install inseq

pip install sacremoses

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # Run in Colab to install local packages
# %pip install bitsandbytes accelerate transformers inseq

!python -c "import inseq; print(inseq.get_version())"

import inseq
from inseq.data.aggregator import SubwordAggregator

"""# Open file"""

pip install "numpy<2.1.0" "pandas==2.2.2"

from google.colab import files

# Upload file
uploaded = files.upload()

import pandas as pd

# Read the tab-separated text into a pandas DataFrame
df = pd.read_csv('/content/source_data-and-contrastive_translations.txt', sep='\t', encoding='windows-1252')

# Access columns and save contents to a list
EN_source = df["EN_source"].tolist()
Opus_MT_DE = df["OPUS-MT_DE"].tolist()
Opus_MT_contrastive = df["OPUS-MT_contrastive"].tolist()


print(f"EN Source: {EN_source[1]}")
print(f"OPUS-MT DE Translation: {Opus_MT_DE[1]}")
print(f"OPUS-MT DE contrastive translation: {Opus_MT_contrastive[1]}")

"""EN Source Satistics: print average length of EN source sentences and standard deviation."""

import numpy as np

#  Calculate lengths, filter out NaN and keep only valid strings
sentence_lengths = [len(sentence.split()) for sentence in EN_source if isinstance(sentence, str)]

# Calculate statistics
average_length = np.mean(sentence_lengths)
std_length = np.std(sentence_lengths, ddof=1)  # ddof=1 for sample std deviation

# Print results
print("=== SENTENCE LENGTH STATISTICS ===")
print(f"Average length: {average_length:.2f} words")
print(f"Standard deviation: {std_length:.2f} words")
print(f"Min length: {min(sentence_lengths)} words")
print(f"Max length: {max(sentence_lengths)} words")
print(f"Total sentences: {len(sentence_lengths)}")

"""# Perform the Contrastive Attribution

We use [inseq](https://github.com/inseq-team/inseq) to compute saliency attribution scores for gender contrastive translations.

Load the Attribution Model: We chose Helsinki's OPUS-MT en-de (same as used for the translations), and we focus on 'saliency'.
"""

import inseq

src = "en"  # source language
trg = "de"  # target language

attribution_model = inseq.load_model(f"Helsinki-NLP/opus-mt-{src}-{trg}", "saliency")

"""### Attribution Visualisation
The cell below visualises inseq's display of saliency attribution for source and target tokens for our given English source and German target sentence. For this project, we focus on the source attribution.

This cell is purely for visualisation purposes, not required for the rest of the notebook (analysis).
"""

# To visualise: not necessary for the rest of the notebook

# Tests just the first few sentences
for i in range(5):
  en = EN_source[i]
  de_orig = Opus_MT_DE[i]
  de_cont = Opus_MT_contrastive[i]


  # Gets original tokens in format [(0, '</s>'), (1, 'deu_Latn'), (2, '▁Beispi'), (3, 'els'), (4, 'atz'), (5, '▁auf'), (6, '▁Eng'), (7, 'lis'), (8, 'ch'), (9, ','), (10, '▁um'), (11, '▁zu'), (12, '▁zeigen'), (13, ','), (14, '▁wes'), (15, 'halb'), (16, '▁dies'), (17, '▁ein'), (18, '▁Problem'), (19, '▁für'), (20, '▁den'), (21, '▁Program'), (22, 'mi'), (23, 'erer'), (24, '▁ist'), (25, '.'), (26, '</s>')]
  orig_tokens = list(enumerate(attribution_model.encode(de_orig, as_targets=True).input_tokens[0]))

  out = attribution_model.attribute(
      en,
      de_orig ,
      contrast_targets=de_cont,
      attribute_target=True,
      attributed_fn="contrast_prob_diff",
      step_scores=["contrast_prob_diff"],
      contrast_targets_alignments=[(i,i) for i in range(len(orig_tokens))],
  )

  out.show()

"""## Methodologies for Approaches 1-5"""

pip install spacy

!python -m spacy download en_core_web_lg

import spacy
nlp = spacy.load("en_core_web_lg")

"""## Run this first. Function that writes all source words and attribution scores to an Excel for further analysis"""

def save_all_normalized_merged_source_attributions_for_first_arrow_word(out, sentence_index, target_words, sheet_name=None):
    """
    Prints the top merged source word attributions for the first target token containing '→',
    after normalizing source attributions for that target token so that they sum to 1.
    Subword tokens are merged into whole words before ranking and printing.
    Also prints the indices of the constituent source tokens.
    Removes the specific target word for this sentence based on sentence_index.
    """
    out_data = out.sequence_attributions[0]
    # Get source tokens and optionally their ids and original index
    source_tokens = [t.token if hasattr(t, 'token') else str(t) for t in out_data.source]
    target_tokens = [t.token if hasattr(t, 'token') else str(t) for t in out_data.target]

    print(f"\n--- SENTENCE {sentence_index + 1} ---")
    print(source_tokens)
    print(target_tokens)

    # Remove end of line character from source tokens
    if "</s>" in source_tokens:
        source_tokens.remove("</s>")

    # Handle alignment window (important for correct attribution indexing)
    attr_pos_start = getattr(out_data, "attr_pos_start", 0)
    attr_pos_end = getattr(out_data, "attr_pos_end", len(target_tokens))
    aligned_target_tokens = target_tokens[attr_pos_start:attr_pos_end]  # Only tokens with attributions

    # Prepare attribution matrix (handle possible 3D tensor)
    saliency_heatmap = out_data.source_attributions
    if hasattr(saliency_heatmap, "shape") and len(saliency_heatmap.shape) == 3:
        saliency_heatmap = saliency_heatmap.sum(dim=2)

    contrast_scores = out_data.step_scores["contrast_prob_diff"]

    # Find first target token containing "→" in the aligned window
    target_word_index = next((i for i, token in enumerate(aligned_target_tokens) if "→" in token), None)
    if target_word_index is None:
        print("No target token containing '→' found.")
        return

    tgt_token = aligned_target_tokens[target_word_index]
    contrast_val = float(contrast_scores[target_word_index])

    # Collect and normalize attribution scores for this target token (column in matrix)
    raw_scores = [
        float(saliency_heatmap[i][target_word_index].item() if hasattr(saliency_heatmap[i][target_word_index], "item") else saliency_heatmap[i][target_word_index])
        for i in range(len(source_tokens))
    ]
    score_sum = sum(raw_scores)
    normalized_scores = [s / score_sum if score_sum != 0 else 0.0 for s in raw_scores]

    # Merge subwords into words and sum their attribution scores
    merged_words = []
    current_word = ""
    current_score = 0.0
    current_indices = []
    current_pos = ""

    for idx, (token, score) in enumerate(zip(source_tokens, normalized_scores)):
        if token.startswith("▁") or token in [".", "</s>"]:  # Start of a new word or special
            if current_word:
                merged_words.append((current_word, current_score, current_indices, current_pos))
            # Start new word
            current_word = token.lstrip("▁")
            current_score = score
            current_indices = [idx]
        else:
            current_word += token
            current_score += score
            current_indices.append(idx)
    # Add last word
    if current_word:
        merged_words.append((current_word, current_score, current_indices, current_pos))


    # Get the specific target word for this sentence
    current_target_word = target_words.get(sentence_index, "").lower()
    print(f"Target word for sentence {sentence_index + 1}: '{current_target_word}'")

    # Create a new list excluding the specific target word for this sentence
    filtered_words = []

    # Extract individual words from compound target words
    all_target_words = set()
    if current_target_word:
        all_target_words.add(current_target_word)  # Add the full compound
        # Add individual words from compounds
        for word_part in current_target_word.split():
            all_target_words.add(word_part)

    print(f"All target words to remove (including compound parts): {all_target_words}")

    for word, score, indices, pos in merged_words:

        # Check if the word itself is in target_words (including compound parts)
        if word.lower().strip(".,:\"'—.-?![]()") in all_target_words:
            print(f"Removing '{word}' - found in target_words")
            continue

        # Check if any individual word from a multi-word phrase is in target_words
        word_parts = word.lower().split()
        if any(part in all_target_words for part in word_parts):
            print(f"Removing '{word}' - contains part in target_words")
            continue

        # Get POS tags for the word
        word = word.strip(".,:\"'—.-?![]()")
        doc = nlp(word)
        pos_tags = [token.pos_ for token in doc]

        # Choose one POS tag (e.g., the first one, or most common one)
        if pos_tags:
          chosen_pos = pos_tags[0]
        elif word == "":
          chosen_pos = "PUNCT"
        else:
          chosen_pos = "UNK"


        # Add the word only once with the chosen POS tag (making sure none of the words include an <unk>)
        if "<unk>" in word:
          filtered_words.append((word.replace("<unk>", "'").strip("'"), score, indices, chosen_pos))
        else:
          filtered_words.append((word, score, indices, chosen_pos))


    merged_words = filtered_words

    # Sort merged words by total attribution score, descending
    merged_words.sort(key=lambda x: x[1], reverse=True)

    print(f"\nFirst target word containing '→' (index {target_word_index + attr_pos_start}): '{tgt_token}'")
    print(f"Contrastive prob diff: {contrast_val:.6f}")

    # Print all merged attributions in order for inspection
    print("All merged source words and their normalized attributions (original order):")
    for word, score, indices, pos in merged_words:
        print(f"  Source word '{word}' (source token idx {indices}): normalized attribution score = {score:.6f}")
    print("")

    df = pd.DataFrame(merged_words, columns=['Source_word', 'Score', 'Indices', 'POS'])
    df['Source_word'] = [word for word, score, indices, pos in merged_words]
    df['Score'] = [score for word, score, indices, pos in merged_words]
    df['POS'] = [pos for word, score, indices, pos in merged_words]

    # Create Contrastive_difference column with value only in first row
    df['Contrastive_difference'] = [(f"{tgt_token}: {contrast_val}") for i in range(len(df))]

    # Reorder columns to match original structure
    df = df[['Contrastive_difference', 'Source_word', 'Score', 'POS']]

    print(df)

    return df

# target words dictionary
target_words = {0: 'flight attendant', 1: 'musician', 2: 'opponent', 3: 'socialite', 4: 'therapist', 5: 'coordinator', 6: 'lover', 7: 'mechanic', 8: 'dancer', 9: 'therapist', 10: 'visitor', 11: 'colleague', 12: 'companion', 13: 'author',
                14: 'clerk', 15: 'student', 16: 'accountant', 17: 'designer', 18: 'baker', 19: 'lover', 20: 'writer', 21: 'winner', 22: 'consumer', 23: 'poet', 24: 'author', 25: 'writer', 26: 'designer', 27: 'bookkeeper', 28: 'clerk',
                29: 'author', 30: 'counselor', 31: 'dancer', 32: 'friend', 33: 'guard', 34: 'officer', 35: 'winner', 36: 'user', 37: 'supporter', 38: 'judge', 39: 'fighter', 40: 'dealer', 41: 'soldier', 42: 'officer', 43: 'player',
                44: 'manager', 45: 'contractor', 46: 'captain', 47: 'farmer', 48: 'maestro', 49: 'construction worker', 50: 'boss', 51: 'driver', 52: 'idiot', 53: 'cook', 54: 'filmmaker', 55: 'admirer', 56: 'follower', 57: 'salesperson',
                58: 'buddy', 59: 'winner'}

# Modified main loop to collect dataframes and save to multi-sheet Excel
dataframes = []
sheet_names = []

for i in range(60):
    en = EN_source[i]
    de_orig = Opus_MT_DE[i]
    de_cont = Opus_MT_contrastive[i]

    # Gets original tokens in format [(0, '</s>'), (1, 'deu_Latn'), (2, '▁Beispi'), (3, 'els'), (4, 'atz'), (5, '▁auf'), (6, '▁Eng'), (7, 'lis'), (8, 'ch'), (9, ','), (10, '▁um'), (11, '▁zu'), (12, '▁zeigen'), (13, ','), (14, '▁wes'), (15, 'halb'), (16, '▁dies'), (17, '▁ein'), (18, '▁Problem'), (19, '▁für'), (20, '▁den'), (21, '▁Program'), (22, 'mi'), (23, 'erer'), (24, '▁ist'), (25, '.'), (26, '</s>')]
    orig_tokens = list(enumerate(attribution_model.encode(de_orig, as_targets=True).input_tokens[0]))

    out = attribution_model.attribute(
        en,
        de_orig,
        contrast_targets=de_cont,
        attribute_target=True,
        attributed_fn="contrast_prob_diff",
        step_scores=["contrast_prob_diff"],
        contrast_targets_alignments=[(i,i) for i in range(len(orig_tokens))],
    )

    print(f"\n=== Processing Sentence {i+1} ===")
    df = save_all_normalized_merged_source_attributions_for_first_arrow_word(out, i, target_words)

    if df is not None:
        dataframes.append(df)
        sheet_names.append(f'Sent_{i+1}')

# Save all dataframes to different sheets in one Excel file
if dataframes:
    filename = f'All_Normalised_attribution_scores.xlsx'
    with pd.ExcelWriter(filename, engine='openpyxl') as writer:
        for df, sheet_name in zip(dataframes, sheet_names):
            df.to_excel(writer, sheet_name=sheet_name, index=False)

    print(f"\nSaved {len(dataframes)} dataframes to '{filename}'")
    print(f"Sheet names: {sheet_names}")
else:
    print("No dataframes to save - no target tokens containing '→' were found.")

"""## APPROACH 1: Function to focus on top X% of attribution scores -- based on ALL Excel file"""

import pandas as pd

def get_top_percentage_scores(attribution_scores, top_percentage, stopwords, target_sheet_name=None):
    """
    Process a specific sheet or all sheets to get top percentage scores
    """
    # If a specific sheet is requested, process only that sheet
    if target_sheet_name is not None:
        sheet_names_to_process = [target_sheet_name] if target_sheet_name in attribution_scores else []
    else:
        # Process all sheets
        sheet_names_to_process = list(attribution_scores.keys())

    # Process the specified sheet(s)
    for sheet_name in sorted(sheet_names_to_process):
        print(f"\nProcessing sheet: {sheet_name}")

        attr_df = attribution_scores[sheet_name]

        # Check if 'Source_word' column exists
        if 'Source_word' in attr_df.columns:
            # Get data from the dataframe
            attr_words = list(attr_df['Source_word'].dropna())
            attr_words = [word for word in attr_words if word.lower() not in stopwords]         ## Remove stopwords
            attr_scores = list(attr_df['Score'].dropna())
            attr_pos = list(attr_df['POS'].dropna())
            contrastive_difference = attr_df['Contrastive_difference'].dropna().iloc[0]
            print(f"Contrastive difference: {contrastive_difference}")

            top_n = max(1, int(len(attr_words) * top_percentage))
            print(f"TOP N: {top_n}")

            # Create a list of tuples (word, score, pos) and sort by score
            word_score_pairs = list(zip(attr_words, attr_scores, attr_pos))
            # Sort by score in descending order to get highest scores first
            word_score_pairs.sort(key=lambda x: x[1], reverse=True)

            # Take top_n pairs
            top_pairs = word_score_pairs[:top_n]

            # Uncomment if you want to print for clarity
            #for word, score, pos in top_pairs:
            #    print(f"  Source word '{word}' [{pos}]: normalized attribution score = {score:.6f}")

            # Create DataFrame with correct structure
            df_top_n = pd.DataFrame({
                'Contrastive_difference': [contrastive_difference] * len(top_pairs),
                'Source_word': [word for word, score, pos in top_pairs],
                'Score': [score for word, score, pos in top_pairs],
                'POS': [pos for word, score, pos in top_pairs]
            })

            print(df_top_n)
            return df_top_n

    # If no valid sheet found, return None
    return None

for top_percentage in [0.05, 0.1, 0.15, 0.2, 0.25]:

  # Main processing code
  attribution_scores = pd.read_excel('All_Normalised_attribution_scores.xlsx', sheet_name=None)
  #top_percentage = 0.10
  dataframes = []
  sheet_names = []
  # Stopwords
  stopwords = ["", "a", "an", "the", "this", "that", "these", "those"]

  for i in range(60):
      print(f"\n=== Processing Sentence {i+1} ===")
      target_sheet_name = f'Sent_{i+1}'  # Assuming your sheets are named like this

      # Pass arguments in correct order: attribution_scores, top_percentage, target_sheet_name
      df = get_top_percentage_scores(attribution_scores, top_percentage, stopwords, target_sheet_name)

      if df is not None:
          dataframes.append(df)
          sheet_names.append(target_sheet_name)

  # Save all dataframes to different sheets in one Excel file
  if dataframes:
      filename = f'All_Normalised_attribution_scores_{top_percentage}.xlsx'
      with pd.ExcelWriter(filename, engine='openpyxl') as writer:
          for df, sheet_name in zip(dataframes, sheet_names):
              df.to_excel(writer, sheet_name=sheet_name, index=False)

      print(f"\nSaved {len(dataframes)} dataframes to '{filename}'")
      print(f"Sheet names: {sheet_names}")
  else:
      print("No dataframes to save - no valid sheets were found.")

"""## APPROACH 2: Write function to focus on attribution scores with a minimum score of X (e.g. 0.07 per score)"""

import pandas as pd

def get_min_score_scores(attribution_scores, min_score, stopwords, target_sheet_name=None):
    """
    Process a specific sheet or all sheets to get source words with a minimum attribution score of X
    """
    # If a specific sheet is requested, process only that sheet
    if target_sheet_name is not None:
        sheet_names_to_process = [target_sheet_name] if target_sheet_name in attribution_scores else []
    else:
        # Process all sheets
        sheet_names_to_process = list(attribution_scores.keys())

    # Process the specified sheet(s)
    for sheet_name in sorted(sheet_names_to_process):
        print(f"\nProcessing sheet: {sheet_name}")

        attr_df = attribution_scores[sheet_name]

        # Check if 'Source_word' column exists
        if 'Source_word' in attr_df.columns:
            # Get data from the dataframe
            attr_words = list(attr_df['Source_word'].dropna())
            attr_words = [word for word in attr_words if word.lower() not in stopwords]         ## Remove stopwords
            attr_scores = list(attr_df['Score'].dropna())
            attr_pos = list(attr_df['POS'].dropna())
            contrastive_difference = attr_df['Contrastive_difference'].dropna().iloc[0]
            print(f"Contrastive difference: {contrastive_difference}")

            # Create a list of tuples (word, score, pos) and sort by score
            word_score_pairs = list(zip(attr_words, attr_scores, attr_pos))
            # Sort by score in descending order to get highest scores first
            word_score_pairs.sort(key=lambda x: x[1], reverse=True)

            print(f"All source words with a minimum score of {min_score}:")
            top_n = 0
            for word, score, pos in word_score_pairs:
                if score > min_score:
                    print(f"  Source word '{word}' [{pos}]: normalized attribution score = {score:.6f}")
                    top_n += 1
            print("")

            top_pairs = word_score_pairs[:top_n]

            # Create DataFrame with correct structure
            df_top_n = pd.DataFrame({
                'Contrastive_difference': [contrastive_difference] * len(top_pairs),
                'Source_word': [word for word, score, pos in top_pairs],
                'Score': [score for word, score, pos in top_pairs],
                'POS': [pos for word, score, pos in top_pairs]
            })

            print(df_top_n)
            return df_top_n

    # If no valid sheet found, return None
    return None

for min_score in [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]:

  # Main processing code
  attribution_scores = pd.read_excel('All_Normalised_attribution_scores.xlsx', sheet_name=None)
  #min_score = 0.07
  dataframes = []
  sheet_names = []
  # Stopwords
  stopwords = ["", "a", "an", "the", "this", "that", "these", "those"]

  for i in range(60):
      print(f"\n=== Processing Sentence {i+1} ===")
      target_sheet_name = f'Sent_{i+1}'  # Assuming your sheets are named like this

      # Pass arguments in correct order: attribution_scores, top_percentage, target_sheet_name
      df = get_min_score_scores(attribution_scores, min_score, stopwords, target_sheet_name)

      if df is not None:
          dataframes.append(df)
          sheet_names.append(target_sheet_name)

  # Save all dataframes to different sheets in one Excel file
  if dataframes:
      filename = f'All_Normalised_attribution_minimum_score_of_{min_score}.xlsx'
      with pd.ExcelWriter(filename, engine='openpyxl') as writer:
          for df, sheet_name in zip(dataframes, sheet_names):
              df.to_excel(writer, sheet_name=sheet_name, index=False)

      print(f"\nSaved {len(dataframes)} dataframes to '{filename}'")
      print(f"Sheet names: {sheet_names}")
  else:
      print("No dataframes to save - no valid sheets were found.")

"""## APPROACH 3: Write a function that selects the 1 top word (highest score) of attributions scores"""

import pandas as pd

def get_highest_scores(attribution_scores, stopwords, target_sheet_name=None):
    """
    Process a specific sheet or all sheets to get top source word based on scores
    """
    # If a specific sheet is requested, process only that sheet
    if target_sheet_name is not None:
        sheet_names_to_process = [target_sheet_name] if target_sheet_name in attribution_scores else []
    else:
        # Process all sheets
        sheet_names_to_process = list(attribution_scores.keys())

    # Process the specified sheet(s)
    for sheet_name in sorted(sheet_names_to_process):
        print(f"\nProcessing sheet: {sheet_name}")

        attr_df = attribution_scores[sheet_name]

        # Check if 'Source_word' column exists
        if 'Source_word' in attr_df.columns:
            # Get data from the dataframe
            attr_words = list(attr_df['Source_word'].dropna())
            attr_words = [word for word in attr_words if word.lower() not in stopwords]         ## Remove stopwords
            attr_scores = list(attr_df['Score'].dropna())
            attr_pos = list(attr_df['POS'].dropna())
            contrastive_difference = attr_df['Contrastive_difference'].dropna().iloc[0]
            print(f"Contrastive difference: {contrastive_difference}")

            # Create a list of tuples (word, score, pos) and sort by score
            word_score_pairs = list(zip(attr_words, attr_scores, attr_pos))
            # Sort by score in descending order to get highest scores first
            word_score_pairs.sort(key=lambda x: x[1], reverse=True)

            top_n = 1
            for word, score, pos in word_score_pairs[:top_n]:
                print(f" Top 1 Source word '{word}' [{pos}]: normalized attribution score = {score:.6f}")
                print("")
            top_pairs = word_score_pairs[:top_n]

            # Create DataFrame with correct structure
            df_top_n = pd.DataFrame({
                'Contrastive_difference': [contrastive_difference] * len(top_pairs),
                'Source_word': [word for word, score, pos in top_pairs],
                'Score': [score for word, score, pos in top_pairs],
                'POS': [pos for word, score, pos in top_pairs]
            })

            print(df_top_n)
            return df_top_n

    # If no valid sheet found, return None
    return None

# Main processing code
attribution_scores = pd.read_excel('All_Normalised_attribution_scores.xlsx', sheet_name=None)
dataframes = []
sheet_names = []
# Stopwords
stopwords = ["", "a", "an", "the", "this", "that", "these", "those"]

for i in range(60):
    print(f"\n=== Processing Sentence {i+1} ===")
    target_sheet_name = f'Sent_{i+1}'  # Assuming your sheets are named like this

    # Pass arguments in correct order: attribution_scores, top_percentage, target_sheet_name
    df = get_highest_scores(attribution_scores, stopwords, target_sheet_name)

    if df is not None:
        dataframes.append(df)
        sheet_names.append(target_sheet_name)

# Save all dataframes to different sheets in one Excel file
if dataframes:
    filename = f'All_Normalised_attribution_scores_top_word.xlsx'
    with pd.ExcelWriter(filename, engine='openpyxl') as writer:
        for df, sheet_name in zip(dataframes, sheet_names):
            df.to_excel(writer, sheet_name=sheet_name, index=False)

    print(f"\nSaved {len(dataframes)} dataframes to '{filename}'")
    print(f"Sheet names: {sheet_names}")
else:
    print("No dataframes to save - no valid sheets were found.")

"""## APPROACH 4: Function to sum attribution scores and take X% PER SENTENCE"""

import pandas as pd

def get_sums_scores_per_sentence(attribution_scores, percent, stopwords, target_sheet_name=None):
    """
    Process a specific sheet or all sheets to get source words based on the
    sum of attribution scores PER SENTENCE and take top X% of that
    """

    # If a specific sheet is requested, process only that sheet
    if target_sheet_name is not None:
        sheet_names_to_process = [target_sheet_name] if target_sheet_name in attribution_scores else []
    else:
        # Process all sheets
        sheet_names_to_process = list(attribution_scores.keys())

    # Process the specified sheet(s)
    for sheet_name in sorted(sheet_names_to_process):
        print(f"\nProcessing sheet: {sheet_name}")

        attr_df = attribution_scores[sheet_name]

        # Check if 'Source_word' column exists
        if 'Source_word' in attr_df.columns:
            # Get data from the dataframe
            attr_words = list(attr_df['Source_word'].dropna())
            attr_words = [word for word in attr_words if word.lower() not in stopwords]         ## Remove stopwords

            attr_scores = list(attr_df['Score'].dropna())
            attr_pos = list(attr_df['POS'].dropna())
            contrastive_difference = attr_df['Contrastive_difference'].dropna().iloc[0]
            print(f"Contrastive difference: {contrastive_difference}")

            # Create a list of tuples (word, score, pos) and sort by score
            word_score_pairs = list(zip(attr_words, attr_scores, attr_pos))
            # Sort by score in descending order to get highest scores first
            word_score_pairs.sort(key=lambda x: x[1], reverse=True)

            selected_words = []
            total_score_per_sentence = 0.0

            for word, score, pos in word_score_pairs:
              print(f"  Source word '{word}' [{pos}]: normalized attribution score = {score:.6f}")
              total_score_per_sentence += score

            print(f"\nTOTAL SCORE FOR {sheet_name}: {total_score_per_sentence:.6f}")

            top_x_percent = total_score_per_sentence * percent
            print(f"TOP {percent*100}% OF {sheet_name}: {top_x_percent:.6f}")

            intermediate_score = 0.0
            for word, score, pos in word_score_pairs:
              if intermediate_score < top_x_percent:
                intermediate_score += score
                selected_words.append((word, score, pos))
              else:
                break

            top_n = len(selected_words)
            print(f"\nFor top {percent*100}%, selected {top_n} words with summed score of {intermediate_score:.6f}:")
            for word, score, pos in selected_words:
              print(f"  Source word '{word}' [{pos}]: normalized attribution score = {score:.6f}")
            print("")

            top_pairs = word_score_pairs[:top_n]

            # Create DataFrame with correct structure
            df_top_n = pd.DataFrame({
                'Contrastive_difference': [contrastive_difference] * len(top_pairs),
                'Source_word': [word for word, score, pos in top_pairs],
                'Score': [score for word, score, pos in top_pairs],
                'POS': [pos for word, score, pos in top_pairs]
            })

            print(df_top_n)
            return df_top_n

    # If no valid sheet found, return None
    return None

for percent in [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]:

  # Main processing code
  attribution_scores = pd.read_excel('All_Normalised_attribution_scores.xlsx', sheet_name=None)
  #percent = 0.2
  dataframes = []
  sheet_names = []
  # Stopwords
  stopwords = ["", "a", "an", "the", "this", "that", "these", "those"]

  for i in range(60):
      print(f"\n=== Processing Sentence {i+1} ===")
      target_sheet_name = f'Sent_{i+1}'  # Assuming your sheets are named like this

      # Pass arguments in correct order: attribution_scores, top_percentage, target_sheet_name
      df = get_sums_scores_per_sentence(attribution_scores, percent, stopwords, target_sheet_name)

      if df is not None:
          dataframes.append(df)
          sheet_names.append(target_sheet_name)

  # Save all dataframes to different sheets in one Excel file
  if dataframes:
      filename = f'All_Normalised_attribution_scores_sums_per_sentence_top_{percent}.xlsx'
      with pd.ExcelWriter(filename, engine='openpyxl') as writer:
          for df, sheet_name in zip(dataframes, sheet_names):
              df.to_excel(writer, sheet_name=sheet_name, index=False)

      print(f"\nSaved {len(dataframes)} dataframes to '{filename}'")
      print(f"Sheet names: {sheet_names}")
  else:
      print("No dataframes to save - no valid sheets were found.")

"""# Extra Analyses

## EXTRA 1: Function to sum attribution scores per sentence and return average score per word overall and average sum
"""

import pandas as pd
import numpy as np  # Added for standard deviation calculation

def get_sums_scores_per_sentence(attribution_scores, stopwords, target_sheet_name=None):
    """
    Process a specific sheet or all sheets to get source words based on the
    sum of attribution scores PER SENTENCE and take top X% of that
    """
    # If a specific sheet is requested, process only that sheet
    if target_sheet_name is not None:
        sheet_names_to_process = [target_sheet_name] if target_sheet_name in attribution_scores else []
    else:
        # Process all sheets
        sheet_names_to_process = list(attribution_scores.keys())

    # Process the specified sheet(s)
    for sheet_name in sorted(sheet_names_to_process):
        print(f"\nProcessing sheet: {sheet_name}")

        attr_df = attribution_scores[sheet_name]

        # Check if 'Source_word' column exists
        if 'Source_word' in attr_df.columns:
            # Get data from the dataframe
            attr_words = list(attr_df['Source_word'].dropna())
            attr_words = [word for word in attr_words if word.lower() not in stopwords]         ## Remove stopwords
            attr_scores = list(attr_df['Score'].dropna())
            attr_pos = list(attr_df['POS'].dropna())
            contrastive_difference = attr_df['Contrastive_difference'].dropna().iloc[0]
            print(f"Contrastive difference: {contrastive_difference}")

            # Create a list of tuples (word, score, pos) and sort by score
            word_score_pairs = list(zip(attr_words, attr_scores, attr_pos))
            # Sort by score in descending order to get highest scores first
            word_score_pairs.sort(key=lambda x: x[1], reverse=True)

            selected_words = []
            total_score_per_sentence = 0.0

            for word, score, pos in word_score_pairs:
              print(f"  Source word '{word}' [{pos}]: normalized attribution score = {score:.6f}")
              total_score_per_sentence += score

            print(f"\nTOTAL SCORE FOR {sheet_name}: {total_score_per_sentence:.6f}")

            # Return both the dataframe and the data for collection
            return attr_scores, total_score_per_sentence

    # If no valid sheet found, return None
    return [], 0.0

# Main processing code
attribution_scores = pd.read_excel('ALL_Normalised_attribution_fullyEdited_scores.xlsx', sheet_name=None)

# Initialize lists to collect all scores and sums
all_scores_per_word = []
all_sums_per_sentence = []
# Stopwords
stopwords = ["", "a", "an", "the", "this", "that", "these", "those"]

for i in range(60):
    print(f"\n=== Processing Sentence {i+1} ===")
    target_sheet_name = f'Sent_{i+1}'  # Assuming your sheets are named like this

    # Get the results from the function
    result = get_sums_scores_per_sentence(attribution_scores, stopwords, target_sheet_name)

    if result[0] is not None:  # Check if df is not None
        scores_per_word, sum_per_sentence = result

        # Collect scores and sums
        all_scores_per_word.extend(scores_per_word)  # Add all individual scores
        all_sums_per_sentence.append(sum_per_sentence)  # Add sentence sum

# Calculate averages and standard deviations
if all_scores_per_word:
    average_score_per_word = sum(all_scores_per_word) / len(all_scores_per_word)
    std_score_per_word = np.std(all_scores_per_word)  # Calculate standard deviation
    print(f"\nAVERAGE SCORE PER WORD (across all sentences): {average_score_per_word:.6f}")
    print(f"STANDARD DEVIATION SCORE PER WORD: {std_score_per_word:.6f}")

if all_sums_per_sentence:
    average_sum_per_sentence = sum(all_sums_per_sentence) / len(all_sums_per_sentence)
    std_sum_per_sentence = np.std(all_sums_per_sentence)  # Calculate standard deviation
    print(f"AVERAGE SUM PER SENTENCE: {average_sum_per_sentence:.6f}")
    print(f"STANDARD DEVIATION SUM PER SENTENCE: {std_sum_per_sentence:.6f}")

print(f"\nTotal individual scores collected, i.e. number of source words: {len(all_scores_per_word)}")
print(f"Total sentences processed: {len(all_sums_per_sentence)}")
print(f"ALL SCORES PER WORD: {all_scores_per_word}")
print(f"ALL SUMS PER SENTENCE: {all_sums_per_sentence}")

# Create visualizations
import matplotlib.pyplot as plt

if all_scores_per_word and all_sums_per_sentence:

    # Plot 1: Distribution of individual word scores
    plt.figure(figsize=(12, 8))
    plt.hist(all_scores_per_word, bins=30, alpha=0.7, color='#3b82f6', edgecolor='#1e40af')
    plt.axvline(average_score_per_word, color='#ef4444', linestyle='--', linewidth=3,
                label=f'Mean: {average_score_per_word:.4f}')
    # Add standard deviation lines
    plt.axvline(average_score_per_word + std_score_per_word, color='#f97316', linestyle=':', linewidth=3,
                label=f'±1 SD: {std_score_per_word:.4f}')
    plt.axvline(average_score_per_word - std_score_per_word, color='#f97316', linestyle=':', linewidth=3)
    plt.title('Distribution of Attribution Scores per Word', fontsize=32, fontweight='medium', pad=20)
    plt.xlabel('Attribution Score', fontsize=28)
    plt.ylabel('Frequency', fontsize=28)
    plt.tick_params(axis='both', which='major', labelsize=22)
    plt.legend(fontsize=20)
    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.show()


    # Plot 2: Sum scores per sentence
    plt.figure(figsize=(12, 8))
    sentence_numbers = list(range(1, len(all_sums_per_sentence) + 1))
    bars = plt.bar(sentence_numbers, all_sums_per_sentence, alpha=0.7, color='#22c55e', edgecolor='#16a34a')
    plt.axhline(average_sum_per_sentence, color='#ef4444', linestyle='--', linewidth=3,
                label=f'Mean: {average_sum_per_sentence:.4f}')
    # Add standard deviation lines
    plt.axhline(average_sum_per_sentence + std_sum_per_sentence, color='#f97316', linestyle=':', linewidth=3,
                label=f'±1 SD: {std_sum_per_sentence:.4f}')
    plt.axhline(average_sum_per_sentence - std_sum_per_sentence, color='#f97316', linestyle=':', linewidth=3)
    plt.title('Sum of Attribution Scores per Sentence', fontsize=32, fontweight='medium', pad=20)
    plt.xlabel('Sentence Number', fontsize=28)
    plt.ylabel('Total Score', fontsize=28)
    plt.tick_params(axis='both', which='major', labelsize=22)
    plt.legend(fontsize=20)
    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.show()

    # Print additional statistics
    print(f"\n=== DETAILED STATISTICS ===")
    print(f"Individual Word Scores:")
    print(f"  Mean: {average_score_per_word:.6f}")
    print(f"  Std Dev: {std_score_per_word:.6f}")
    print(f"  Min: {min(all_scores_per_word):.6f}")
    print(f"  Max: {max(all_scores_per_word):.6f}")
    print(f"  Range: {max(all_scores_per_word) - min(all_scores_per_word):.6f}")

    print(f"\nSentence Totals:")
    print(f"  Mean: {average_sum_per_sentence:.6f}")
    print(f"  Std Dev: {std_sum_per_sentence:.6f}")
    print(f"  Min: {min(all_sums_per_sentence):.6f}")
    print(f"  Max: {max(all_sums_per_sentence):.6f}")
    print(f"  Range: {max(all_sums_per_sentence) - min(all_sums_per_sentence):.6f}")

"""## EXTRA 2: Write function that prints all source words + attribution scores and then, using the Excel file of annotations, mark all source words that have also been annotated."""

import pandas as pd

def mark_source_words_with_annotations(out, sentence_index, target_words, annotations):
    """
    Prints the top merged source word attributions for the first target token containing '→',
    after normalizing source attributions for that target token so that they sum to 1.
    Subword tokens are merged into whole words before ranking and printing.
    Also prints the indices of the constituent source tokens.
    Removes the specific target word for this sentence based on sentence_index.
    Compares the attribution source words to the annotations. Marks all source words that have also been annotated.
    """
    out_data = out.sequence_attributions[0]
    # Get source tokens and optionally their ids and original index
    source_tokens = [t.token if hasattr(t, 'token') else str(t) for t in out_data.source]
    target_tokens = [t.token if hasattr(t, 'token') else str(t) for t in out_data.target]

    print(f"\n--- SENTENCE {sentence_index + 1} ---")

    print(source_tokens)
    print(target_tokens)

    # Remove end of line character from source tokens
    if "</s>" in source_tokens:
        source_tokens.remove("</s>")

    # Handle alignment window (important for correct attribution indexing)
    attr_pos_start = getattr(out_data, "attr_pos_start", 0)
    attr_pos_end = getattr(out_data, "attr_pos_end", len(target_tokens))
    aligned_target_tokens = target_tokens[attr_pos_start:attr_pos_end]  # Only tokens with attributions

    # Prepare attribution matrix (handle possible 3D tensor)
    saliency_heatmap = out_data.source_attributions
    if hasattr(saliency_heatmap, "shape") and len(saliency_heatmap.shape) == 3:
        saliency_heatmap = saliency_heatmap.sum(dim=2)

    contrast_scores = out_data.step_scores["contrast_prob_diff"]

    # Find first target token containing "→" in the aligned window
    target_word_index = next((i for i, token in enumerate(aligned_target_tokens) if "→" in token), None)
    if target_word_index is None:
        print("No target token containing '→' found.")
        return

    tgt_token = aligned_target_tokens[target_word_index]
    contrast_val = float(contrast_scores[target_word_index])

    # Collect and normalize attribution scores for this target token (column in matrix)
    raw_scores = [
        float(saliency_heatmap[i][target_word_index].item() if hasattr(saliency_heatmap[i][target_word_index], "item") else saliency_heatmap[i][target_word_index])
        for i in range(len(source_tokens))
    ]
    score_sum = sum(raw_scores)
    normalized_scores = [s / score_sum if score_sum != 0 else 0.0 for s in raw_scores]

    # Merge subwords into words and sum their attribution scores
    merged_words = []
    current_word = ""
    current_score = 0.0
    current_indices = []

    for idx, (token, score) in enumerate(zip(source_tokens, normalized_scores)):
        if token.startswith("▁") or token in [".", "</s>"]:  # Start of a new word or special
            if current_word:
                merged_words.append((current_word, current_score, current_indices))
            # Start new word
            current_word = token.lstrip("▁")
            current_score = score
            current_indices = [idx]
        else:
            current_word += token
            current_score += score
            current_indices.append(idx)
    # Add last word
    if current_word:
        merged_words.append((current_word, current_score, current_indices))

    # Get the specific target word for this sentence
    current_target_word = target_words.get(sentence_index, "").lower()
    print(f"Target word for sentence {sentence_index + 1}: '{current_target_word}'")

    # Create a new list excluding the specific target word for this sentence
    filtered_words = []

    # Extract individual words from compound target words
    all_target_words = set()
    if current_target_word:
        all_target_words.add(current_target_word)  # Add the full compound
        # Add individual words from compounds
        for word_part in current_target_word.split():
            all_target_words.add(word_part)

    print(f"All target words to remove (including compound parts): {all_target_words}")

    for word, score, indices in merged_words:
        word_stripped = word.strip(".,:\"'—.-?![]()")
        word_lower = word_stripped.lower()

        # Check if the word itself is in target_words (including compound parts)
        if word_lower in all_target_words:
            print(f"Removing '{word_stripped}' - found in target_words")
            continue

        # Check if any individual word from a multi-word phrase is in target_words
        word_parts = word_lower.split()
        if any(part in all_target_words for part in word_parts):
            print(f"Removing '{word_stripped}' - contains part in target_words")
            continue

        # If word doesn't match any target words, keep it
        if word_stripped != "":
            filtered_words.append((word_stripped, score, indices))

    merged_words = filtered_words

    # Sort merged words by total attribution score, descending
    merged_words.sort(key=lambda x: x[1], reverse=True)

    print(f"\nFirst target word containing '→' (index {target_word_index + attr_pos_start}): '{tgt_token}'")
    print(f"Contrastive prob diff: {contrast_val:.6f}")

    ## Now compare the attribution source words to the annotations ##
    stopwords = ["", "a", "an", "the", "this", "that", "these", "those"]

    merged_words = [(word, score, indices) for word, score, indices in merged_words
                if word.lower() not in stopwords]

    # Get the current sentence sheet name (e.g., "Sent_1" for sentence_index=0)
    current_sheet_name = f"Sent_{sentence_index + 1}"


    # Check if the current sheet exists in annotations
    if current_sheet_name not in annotations:
        print(f"Warning: Sheet '{current_sheet_name}' not found in annotations")
        # Print all words without annotation marking
        print("All merged source words and their normalized attributions (original order):")
        for word, score, indices in merged_words:
            print(f"Source word '{word}' (source token idx {indices}): normalized attribution score = {score:.6f}")
        print("")
        return

    # Get annotated words for the current sentence only
    annot_df = annotations[current_sheet_name]
    raw_annot_words = set(annot_df['Source_word'].dropna())

    # Split compound words and create expanded annotation set
    annot_words = set()
    for word in raw_annot_words:
        if word not in stopwords:
            # Add the original word
            annot_words.add(word)
            # Split compound words and add individual parts
            word_parts = word.split()
            if len(word_parts) > 1:  # Only if it's actually a compound
                for part in word_parts:
                    if part not in stopwords:
                        annot_words.add(part)

    # Convert back to list for compatibility
    annot_words = list(annot_words)

    # Prepare data for DataFrame with annotation status
    df_data = []

    print("\nAll merged source words and their normalised attributions:")
    for word, score, indices in merged_words:
        is_annotated = word in annot_words
        matched_sheet = current_sheet_name if is_annotated else None

        if is_annotated:
            print(f"Source word '\033[31m{word}\033[0m': normalised attribution score = {score:.6f}")
        else:
            print(f"Source word '{word}': normalised attribution score = {score:.6f}")

        # Add to DataFrame data
        df_data.append({
            'Source_word': word,
            'Score': score,
            'Indices': str(indices),
            'Is_Annotated': is_annotated,
            'Matched_Sheet': matched_sheet,
            'Annotation_Status': 'Annotated' if is_annotated else 'Not Annotated'
        })

    print("")

"""Run the function and make sure you've also uploaded the Excel annotations file at this point, as we'll be calling it below."""

# Your target words dictionary
target_words = {0: 'flight attendant', 1: 'musician', 2: 'opponent', 3: 'socialite', 4: 'therapist', 5: 'coordinator', 6: 'lover', 7: 'mechanic', 8: 'dancer', 9: 'therapist', 10: 'visitor', 11: 'colleague', 12: 'companion', 13: 'author',
                14: 'clerk', 15: 'student', 16: 'accountant', 17: 'designer', 18: 'baker', 19: 'lover', 20: 'writer', 21: 'winner', 22: 'consumer', 23: 'poet', 24: 'author', 25: 'writer', 26: 'designer', 27: 'bookkeeper', 28: 'clerk',
                29: 'author', 30: 'counselor', 31: 'dancer', 32: 'friend', 33: 'guard', 34: 'officer', 35: 'winner', 36: 'user', 37: 'supporter', 38: 'judge', 39: 'fighter', 40: 'dealer', 41: 'soldier', 42: 'officer', 43: 'player',
                44: 'manager', 45: 'contractor', 46: 'captain', 47: 'farmer', 48: 'maestro', 49: 'construction worker', 50: 'boss', 51: 'driver', 52: 'idiot', 53: 'cook', 54: 'filmmaker', 55: 'admirer', 56: 'follower', 57: 'salesperson',
                58: 'buddy', 59: 'winner'}

#annotations = pd.read_excel('All_annotations_duplicates_removed_majority_min_two_agree.xlsx', sheet_name=None)
annotations = pd.read_excel('Annotations_all_majority.xlsx', sheet_name=None)

# Updated main loop
for i in range(60):  # Iterate through 60 sentences
    en = EN_source[i]
    de_orig = Helsinki_Opus_MT[i]
    #de_cont = Helsinki_Opus_MT_edited[i]
    de_cont = Helsinki_Opus_MT_fully_edited[i]

    # Gets original tokens
    orig_tokens = list(enumerate(attribution_model.encode(de_orig, as_targets=True).input_tokens[0]))

    out = attribution_model.attribute(
        en,
        de_orig,
        contrast_targets=de_cont,
        attribute_target=True,
        attributed_fn="contrast_prob_diff",
        step_scores=["contrast_prob_diff"],
        contrast_targets_alignments=[(i,i) for i in range(len(orig_tokens))],
        show_progress=False                                                       ### Can be commented out if you want the information. Not needed to print though.
    )

    # Pass the sentence index and target_words dictionary to the function
    mark_source_words_with_annotations(out, i, target_words, annotations)

"""### Saving to Excel"""

import pandas as pd

def mark_source_words_with_annotations(out, sentence_index, target_words, annotations, sheet_name=None):
    """
    Prints the top merged source word attributions for the first target token containing '→',
    after normalizing source attributions for that target token so that they sum to 1.
    Subword tokens are merged into whole words before ranking and printing.
    Also prints the indices of the constituent source tokens.
    Removes the specific target word for this sentence based on sentence_index.
    Compares the attribution source words to the annotations. Marks all source words that have also been annotated.
    Returns DataFrame with annotation status for Excel export.
    """
    out_data = out.sequence_attributions[0]
    # Get source tokens and optionally their ids and original index
    source_tokens = [t.token if hasattr(t, 'token') else str(t) for t in out_data.source]
    target_tokens = [t.token if hasattr(t, 'token') else str(t) for t in out_data.target]

    print(f"\n--- SENTENCE {sentence_index + 1} ---")
    print(source_tokens)
    print(target_tokens)

    # Remove end of line character from source tokens
    if "</s>" in source_tokens:
        source_tokens.remove("</s>")

    # Handle alignment window (important for correct attribution indexing)
    attr_pos_start = getattr(out_data, "attr_pos_start", 0)
    attr_pos_end = getattr(out_data, "attr_pos_end", len(target_tokens))
    aligned_target_tokens = target_tokens[attr_pos_start:attr_pos_end]  # Only tokens with attributions

    # Prepare attribution matrix (handle possible 3D tensor)
    saliency_heatmap = out_data.source_attributions
    if hasattr(saliency_heatmap, "shape") and len(saliency_heatmap.shape) == 3:
        saliency_heatmap = saliency_heatmap.sum(dim=2)

    contrast_scores = out_data.step_scores["contrast_prob_diff"]

    # Find first target token containing "→" in the aligned window
    target_word_index = next((i for i, token in enumerate(aligned_target_tokens) if "→" in token), None)
    if target_word_index is None:
        print("No target token containing '→' found.")
        return None

    tgt_token = aligned_target_tokens[target_word_index]
    contrast_val = float(contrast_scores[target_word_index])

    # Collect and normalize attribution scores for this target token (column in matrix)
    raw_scores = [
        float(saliency_heatmap[i][target_word_index].item() if hasattr(saliency_heatmap[i][target_word_index], "item") else saliency_heatmap[i][target_word_index])
        for i in range(len(source_tokens))
    ]
    score_sum = sum(raw_scores)
    normalized_scores = [s / score_sum if score_sum != 0 else 0.0 for s in raw_scores]

    # Merge subwords into words and sum their attribution scores
    merged_words = []
    current_word = ""
    current_score = 0.0
    current_indices = []

    for idx, (token, score) in enumerate(zip(source_tokens, normalized_scores)):
        if token.startswith("▁") or token in [".", "</s>"]:  # Start of a new word or special
            if current_word:
                merged_words.append((current_word, current_score, current_indices))
            # Start new word
            current_word = token.lstrip("▁")
            current_score = score
            current_indices = [idx]
        else:
            current_word += token
            current_score += score
            current_indices.append(idx)
    # Add last word
    if current_word:
        merged_words.append((current_word, current_score, current_indices))

    # Get the specific target word for this sentence
    current_target_word = target_words.get(sentence_index, "").lower()
    print(f"Target word for sentence {sentence_index + 1}: '{current_target_word}'")

    # Create a new list excluding the specific target word for this sentence
    filtered_words = []

    # Extract individual words from compound target words
    all_target_words = set()
    if current_target_word:
        all_target_words.add(current_target_word)  # Add the full compound
        # Add individual words from compounds
        for word_part in current_target_word.split():
            all_target_words.add(word_part)

    print(f"All target words to remove (including compound parts): {all_target_words}")

    for word, score, indices in merged_words:
        word_stripped = word.strip(".,:\"'—.-?![]()")
        word_lower = word_stripped.lower()

        # Check if the word itself is in target_words (including compound parts)
        if word_lower in all_target_words:
            print(f"Removing '{word_stripped}' - found in target_words")
            continue

        # Check if any individual word from a multi-word phrase is in target_words
        word_parts = word_lower.split()
        if any(part in all_target_words for part in word_parts):
            print(f"Removing '{word_stripped}' - contains part in target_words")
            continue

        # If word doesn't match any target words, keep it
        filtered_words.append((word_stripped, score, indices))

    merged_words = filtered_words

    # Sort merged words by total attribution score, descending
    merged_words.sort(key=lambda x: x[1], reverse=True)

    print(f"\nFirst target word containing '→' (index {target_word_index + attr_pos_start}): '{tgt_token}'")
    print(f"Contrastive prob diff: {contrast_val:.6f}")


    ## Now compare the attribution source words to the annotations ##
    stopwords = ["a", "and"]

    # Get the current sentence sheet name (e.g., "Sent_1" for sentence_index=0)
    current_sheet_name = f"Sent_{sentence_index + 1}"

    # Check if the current sheet exists in annotations
    if current_sheet_name not in annotations:
        print(f"Warning: Sheet '{current_sheet_name}' not found in annotations")
        # Print all words without annotation marking
        print("All merged source words and their normalized attributions (original order):")
        for word, score, indices in merged_words:
            print(f"Source word '{word}' (source token idx {indices}): normalized attribution score = {score:.6f}")
        print("")
        return


    # Get annotated words for the current sentence only
    annot_df = annotations[current_sheet_name]
    raw_annot_words = set(annot_df['Source_word'].dropna())

    # Split compound words and create expanded annotation set
    annot_words = set()
    for word in raw_annot_words:
        if word not in stopwords:
            # Add the original word
            annot_words.add(word)
            # Split compound words and add individual parts
            word_parts = word.split()
            if len(word_parts) > 1:  # Only if it's actually a compound
                for part in word_parts:
                    if part not in stopwords:
                        annot_words.add(part)

    # Convert back to list for compatibility
    annot_words = list(annot_words)

    # Prepare data for DataFrame with annotation status
    df_data = []

    print("All merged source words and their normalized attributions (original order):")
    for word, score, indices in merged_words:
        is_annotated = word in annot_words
        matched_sheet = current_sheet_name if is_annotated else None

        if is_annotated:
            print(f"Source word '\033[31m{word}\033[0m' (source token idx {indices}): normalized attribution score = {score:.6f}")
        else:
            print(f"Source word '{word}' (source token idx {indices}): normalized attribution score = {score:.6f}")

        # Add to DataFrame data
        df_data.append({
            'Source_word': word,
            'Score': score,
            'Indices': str(indices),
            'Is_Annotated': is_annotated,
            'Matched_Sheet': matched_sheet,
            'Annotation_Status': 'Annotated' if is_annotated else 'Not Annotated'
        })

    print("")

    # Create DataFrame
    df = pd.DataFrame(df_data)

    # Add contrastive difference column (only in first row)
    df['Contrastive_difference'] = [f"{tgt_token}: {contrast_val}" if i == 0 else None for i in range(len(df))]

    # Reorder columns
    df = df[['Contrastive_difference', 'Source_word', 'Score', 'Is_Annotated', 'Annotation_Status', 'Matched_Sheet', 'Indices']]

    print(df)
    return df

if __name__ == "__main__":
    # target words dictionary
    target_words = {0: 'flight attendant', 1: 'musician', 2: 'opponent', 3: 'socialite', 4: 'therapist', 5: 'coordinator', 6: 'lover', 7: 'mechanic', 8: 'dancer', 9: 'therapist', 10: 'visitor', 11: 'colleague', 12: 'companion', 13: 'author',
                    14: 'clerk', 15: 'student', 16: 'accountant', 17: 'designer', 18: 'baker', 19: 'lover', 20: 'writer', 21: 'winner', 22: 'consumer', 23: 'poet', 24: 'author', 25: 'writer', 26: 'designer', 27: 'bookkeeper', 28: 'clerk',
                    29: 'author', 30: 'counselor', 31: 'dancer', 32: 'friend', 33: 'guard', 34: 'officer', 35: 'winner', 36: 'user', 37: 'supporter', 38: 'judge', 39: 'fighter', 40: 'dealer', 41: 'soldier', 42: 'officer', 43: 'player',
                    44: 'manager', 45: 'contractor', 46: 'captain', 47: 'farmer', 48: 'maestro', 49: 'construction worker', 50: 'boss', 51: 'driver', 52: 'idiot', 53: 'cook', 54: 'filmmaker', 55: 'admirer', 56: 'follower', 57: 'salesperson',
                    58: 'buddy', 59: 'winner'}

    # Reads in annotations file
    annotations = pd.read_excel('All_annotations_duplicates_removed_majority_min_two_agree.xlsx', sheet_name=None)

    # Modified main loop to collect dataframes and save to multi-sheet Excel
    dataframes = []
    sheet_names = []

    for i in range(60):
      en = EN_source[i]
      de_orig = Helsinki_Opus_MT[i]
      #de_cont = Helsinki_Opus_MT_edited[i]
      de_cont = Helsinki_Opus_MT_fully_edited[i]

      # Gets original tokens
      orig_tokens = list(enumerate(attribution_model.encode(de_orig, as_targets=True).input_tokens[0]))

      out = attribution_model.attribute(
          en,
          de_orig,
          contrast_targets=de_cont,
          attribute_target=True,
          attributed_fn="contrast_prob_diff",
          step_scores=["contrast_prob_diff"],
          contrast_targets_alignments=[(i,i) for i in range(len(orig_tokens))],
          show_progress=False                                                       ### Can be commented out if you want the information. Not needed to print though.
      )

      print(f"\n=== Processing Sentence {i+1} ===")
      df = mark_source_words_with_annotations(out, i, target_words, annotations)

      if df is not None:
          dataframes.append(df)
          sheet_names.append(f'Sent_{i+1}')

    # Save all dataframes to different sheets in one Excel file
    if dataframes:
        filename = f'Highlighted_attribution_scores_that_were_annotations.xlsx'
        with pd.ExcelWriter(filename, engine='openpyxl') as writer:
            for df, sheet_name in zip(dataframes, sheet_names):
                df.to_excel(writer, sheet_name=sheet_name, index=False)

        print(f"\nSaved {len(dataframes)} dataframes to '{filename}'")
        print(f"Sheet names: {sheet_names}")

        # Print summary statistics
        total_annotated = sum(df['Is_Annotated'].sum() for df in dataframes)
        total_words = sum(len(df) for df in dataframes)
        print(f"Total words processed: {total_words}")
        print(f"Words found in annotations: {total_annotated}")
        print(f"Percentage annotated: {(total_annotated/total_words)*100:.2f}%")
    else:
        print("No dataframes to save - no target tokens containing '→' were found.")

"""## EXTRA 3: How I found to use "aggregate" function to get the actual source attribution ranks (although the actual values are still slightly different)"""

import inspect
print(inspect.getsource(out.show))

print(type(out.sequence_attributions[0]))
print(dir(out.sequence_attributions[0]))

import inspect
print(inspect.getsource(out.sequence_attributions[0].show))

from inseq import show_attributions

# Suppose 'out' is your FeatureAttributionOutput object from attribution_model.attribute()
aggregated = out.aggregate()  # or out.aggregate(aggregator) if you want to specify

# Then call show_attributions with these parameters (replace min_val etc. as needed)
show_attributions(aggregated, min_val=None, max_val=None, display=True, return_html=False)

agg = out.aggregate()
print(agg)